### ISSUE TITLE
Update Deseq2 to version 2.11.40.1 on main

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#101]
Latest in MTS as of 2018-02-21: https://toolshed.g2.bx.psu.edu/view/iuc/deseq2/3660c9088494

**Comment by martenson** [comment]
updated on Main in https://github.com/galaxyproject/usegalaxy-playbook/commit/34a4dd4815981e23ec7f3a436048cf990c3146ce

**Comment by jennaj** [comment]
Ok, was finally got back to testing this tool upgrade late last week through this week so far. There are problems.

**Details tl;dr,** ha, but read anyway when have time. Some of this might help in figuring out what all the root issues are, so want to capture the current behavior/test results, in case others have insight/knowledge that can help pinpoint all derivative issues plus have a record of what was tested, linked issues, tool updates, installs, workflow/tutorial usage, etcetera. 

Plus there are a new few bug reports (5 so far) for DeSeq2 since the update that present with the same vague error report content. Inputs appear to be fine - am testing using tutorial data that I know worked with the overall tutorial workflows before (and with prior tool versions) and produce expected results. Not yet sure exactly what the problems(s) are yet, but some seem to be related to paired-end collection inputs, or that is just one usage case that is problematic. Am continuing with tests are in progress.

**Related:** 

1. This tool (and others) **no longer recognize inputs that are still processing**, in particular collections. Dan brought this up as an issue already (individual and collection datasets are involved) and I need to check the status on that. The prior version of the tool works Ok for all of these new problematic functions/use cases. This might need a tool repo ticket or possibly a Galaxy dist ticket -- that is part of the tests. 

2. During testing, also found that **FeatureCounts** has odd behavior (with one of the inputs accepted by the tool, - but that is almost certainly problem with the tool itself and I'll open a distinct ticket pinging the author about the problem. Specifically, the newer version does not recognize GTF datasets from the history. I have screenshots/test histories and will use those when creating tickets. Once fixed, we'll need to update Main with the new revision (and the eu/au mirrors possibly as well). Some discussion about other issues is already posted in the existing tool repo ticket, see https://github.com/galaxyproject/tools-iuc/issues/1754#issuecomment-370161080.

3. I think the **htseq-count** problems related to STAR input resolved (https://github.com/galaxyproject/usegalaxy-playbook/issues/84) but need to go back to that test history to confirm (including using the output with DeSeq2, then close out the ticket once resolved.


**These tools are all linked in tutorials intended to run on Main, so getting all to work together is part of what I am meta-testing.**

I can state that dependency issues do not seem to be a factor (for any tools above), so we did install these correctly, usage/tool functionality is the problem. **So please do not close this out yet -- we should have all related ticket/issues resolved/on main, or at least ticketed/in progress, to get the tutorial workflows using these tools fully functional. Main is the priority, but other mirrors, or when installed in a local/docker/cloud need to work, too**. Meaning, the best functional version of tool(s) are created (as needed), published to the MTS, and installed on Main/mirrors -- or we have a plan in place to do that. I am running parallel tests at https://usegalaxy.eu for comparisons to determine if issues are server-specific or with the updated tool wrappers themselves - each issue has a distinct root issue (possible exception: paired-end collection input issues, if turns out to be actual issue and and not a derivative problem).

Will do best to get this all done by Fri, early next week at the latest, depends on the complexity of the root cause for odd results/failures and usage when not using a workflow. End users should be able to run the analysis directly in the history, not just as part of a workflow, and produce scientifically valid results with either usage, both in 18.01 and then the new freeze for 18.05 once installed on Main, so we can catch/fix distro problems before the final Galaxy 18.05 release.

Much complexity here - so please bear with me as I juggle support Qs with testing/issue creation, and untangle the related problems. These are our primary RNA-seq analysis tools. It is important to avoid any surprises during GCC training/hacks with the Docker/Cloudman instances used in June.

**Comment by jennaj** [comment]
Retesting -- all of the above issues should be resolved now.

**Comment by jennaj** [comment]
Completely retesting. Issues with featurecount/htseq were interfering with this test.

**Comment by jennaj** [comment]
Test history: https://usegalaxy.org/u/jen/h/test-history-star-hisat2-featurecounts-htseq-deseq2-better

Works fine with individual datasets, the collection test is still running but seems Ok. 

Closing will re-open if that fails (dependency) or open a new ticket (tool bug).

**Comment by jennaj** [comment]
Paired collection as an input work now
