### ISSUE TITLE
Upload displays FTP files while the the transfer is in progress - no warnings, can be imported as partial datasets

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#103]
Not sure how we can trap an aborted/resumed transfer and keep it out of the Upload tool, but it seems like we could catch those _transfers in progress (even if resumed) and not display them until done_. This might be a bug.

These are semi-large data (~4 GB each BAM, 14 GB for the SAM). I have had to accept cert/resume a few times. Many users load much larger datasets. Resuming is likely common.

A few more details are included here: https://github.com/galaxyproject/usegalaxy-playbook/issues/102#issuecomment-373589583 and here https://github.com/galaxyproject/tools-iuc/issues/1774#issuecomment-373589810

Thoughts? @guerler @natefoo

**Example** 

UI/Upload tool versus Filezilla, screenshots taken a few mins apart:

<img width="871" alt="screen shot 2018-03-15 at 7 25 43 pm" src="https://user-images.githubusercontent.com/8999735/37500506-21130b4a-2887-11e8-9386-3df32e80db65.png">

<img width="871" alt="screen shot 2018-03-15 at 7 25 59 pm" src="https://user-images.githubusercontent.com/8999735/37500507-213c9a78-2887-11e8-93dc-694b9a8d6793.png">

Then the transfer. Note that all four have started up, but only three remain in the Upload tool at this point. Results are in the different tickets above that including testing results for the final datatype assignment and related comments.

<img width="880" alt="screen shot 2018-03-15 at 7 48 48 pm" src="https://user-images.githubusercontent.com/8999735/37501209-841ec4f6-288a-11e8-9edf-039879555561.png">

<img width="570" alt="screen shot 2018-03-15 at 7 49 05 pm" src="https://user-images.githubusercontent.com/8999735/37501210-843d5272-288a-11e8-99bb-916fa795d912.png">

<img width="1050" alt="screen shot 2018-03-15 at 7 50 12 pm" src="https://user-images.githubusercontent.com/8999735/37501211-8454db04-288a-11e8-9cbd-562d377a47d3.png">

**Comment by jennaj** [comment]
After some datasets fully moved into the history, the FTP area updates to reflect those datasets still in an active/resumed transfer mode.  

This is good because datasets loaded into the history, sticking around in the FTP area, was a prior bug fix by @guerler (thank you!!).

But also not-so-good, because no end users should access/history load those transferring files yet - are incomplete.

<img width="583" alt="screen shot 2018-03-15 at 9 15 15 pm" src="https://user-images.githubusercontent.com/8999735/37503566-65c00e5a-2896-11e8-8b32-ad74ad3496a6.png">

That's it! - we can follow up from here and decide what to do.

**Comment by natefoo** [comment]
Because the upload process is external to Galaxy there is really no way for it to know that the upload is incomplete. Verifying that the upload succeeded is up to the user. In addition to the file size on the info page, users can use the [hash tool](https://usegalaxy.org/?tool_id=secure_hash_message_digest&version=0.0.1&__identifer=qmmure84t8c) to verify that the file uploaded matches their local file.

We could add size and modification time columns to the FTP file selection window, which would allow for a quick visual indicator, but to be sure, users should be paying attention to their FTP client.

**Comment by martenson** [comment]
> We could add size and modification time columns to the FTP file selection window

it already has the size column


I agree that the users are in charge here, they need to make sure to understand handling of their own files.

**Comment by natefoo** [comment]
Oh... right... it's right there in the screenshot, ha.

**Comment by erasche** [comment]
Maybe error prone but could decrease complaints?: when listing FTP files could we `time.sleep(1)` and compare filesizes? Ignoring those that have changed?

**Comment by natefoo** [comment]
I considered this but worried it'd result in many false positives for bursty connections.

**Comment by jennaj** [comment]
Ok, it sounds like we can't keep _actively transferring_ files out of the Upload/FTP listing. That was my primary question -- if there was some way to do that.

Closing, but please re-open if a working solution comes up. Partial FTP uploads is the root issue with many downstream tool errors and are difficult to diagnose. I suspect some users don't even know it is going on (incomplete results from downstream tools) and so never report a problem, just think the results are odd when using Galaxy. What happens depends on the datatype and tool(s) used. 

Agree, not resuming/tracking the load is one thing users should do -- but I don't think the common (or new!) sci user expects the datasets to show up in the GUI until the transfer is completed. Now, could still be partial, if they didn't resume and the connection was interrupted, but nothing we can do about that case on our side.

I'll add some usage-warning blurb to the FTP upload FAQ in the hub and link to the Troubleshooting FAQ. Might help, or at least gives a handle/link to explain proper usage when sending bug/biostars replies.
