### ISSUE TITLE
Mappers label BAM output with fastq dbkey, not aligned genome dbkey

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#104]
Test history: https://usegalaxy.org/u/jen/h/test-history-mappers

**1 - fq input assigned a dbkey, bam assigned same dbkey, BUT NOT the target genome dbkey**

One example for **RNA STAR** (dataset 8). 

**HISAT2** presents with the same type of problem (dataset 24).

<img width="1230" alt="screen shot 2018-03-19 at 5 31 15 pm" src="https://user-images.githubusercontent.com/8999735/37629414-dc6a6cd2-2b9b-11e8-9ae7-93dbfbbb21e1.png">

**Comment by jennaj** [comment]
Other tests in the same history (in progress). Will open distinct tickets depending on the outcome.

**2 - mappers can have options set that require gtf, but when none given, no warning (before or after job submitted/finishes). The issue for STAR exists here, but impacts HISAT2 as well.** https://github.com/galaxyproject/tools-iuc/issues/1777

**3 - hisat2 "new mapping report" ? Not labeled any differently from "original mapping report" - and just one output?**

**4 - multiqc run on all mapping reports (mixed - some for mqc, some not)**

**5 - multiqc run with only "new mapping report"**

**Comment by jennaj** [comment]
Multi-QC problems in test history - not ticketed yet.

Details in bug report jen/bx dated 3-23-18

**Comment by jennaj** [comment]
Retesting (although it was there yesterday and user's have reported it since first found)

**Comment by jennaj** [comment]
Same test history, jobs in progress

dataset 12, HISAT 2.1.0 , rerun dataset 86:  

dataset 8, STAR version 2.5.2b-0, rerun dataset 89:

**Comment by jennaj** [comment]
Same results. Was this fixed in 18.05? Do I need open tickets against the mapper's repos?

Bowtie2 does not have this problem (and never did) - just STAR and HISAT2

This seems important eg overall usability for thse very popular tools.

sos @dannon @natefoo

**Comment by natefoo** [comment]
Is this a new change from previous behavior? Did the mappers assign the aligned dbkey to the output in older releases? If so, I wouldn't know where to look for this one, someone more familiar with the tool framework might know.

**Comment by blankenberg** [comment]
HISAT2 should be fixed with https://github.com/galaxyproject/tools-iuc/pull/1902

Other mappers also likely need to be individually fixed in a similar fashion.

**Comment by jennaj** [comment]
Thank you! Tracking the tool update here: https://github.com/galaxyproject/usegalaxy-playbook/issues/132

Will create one for STAR if/once you PR that, please post back again here with PR link, very much helps.

Bowtie2 doesn't have this problem, think it is just those two. Can close all these out together once done & test pass, end-users are following this one.

**Comment by jennaj** [comment]
Retested all mappers, test history https://usegalaxy.org/u/jen/h/test-history-mappers

Problematic

 - [ ] HISAT2 2.1.0 - now fixed, data 109-110
 - [ ] RNA STAR 2.5.2b-0 - fix pending, data 111-116
 - [ ] Bowtie2 2.3.4.1 - fix pending, data 117-120

Assign database correctly

 - BWA 0.7.17.4 - data 121-122
 - BWA-Mem 0.7.17.1 - data 123-124

**Whoever fixes Bowtie2** (not known to be a problem before), be sure to output the log file to the history if you self-test. Result datasets can capture a different dbkey (or none at all) in the log versus the BAM output, depending on if the input fastq has database assigned or not.

All of these should have hg19 assigned, not hg38 or ? or mixed assignments for same run

<img width="247" alt="screen shot 2018-06-06 at 6 52 55 am" src="https://user-images.githubusercontent.com/8999735/41043490-e59ac93c-6958-11e8-8aaa-699f411a40b0.png">
<img width="248" alt="screen shot 2018-06-06 at 6 53 19 am" src="https://user-images.githubusercontent.com/8999735/41043492-e5b5197c-6958-11e8-9b46-9523906ef4c3.png">

**Comment by jennaj** [comment]
tests pass for all three tools
