### ISSUE TITLE
Circos Builder (Galaxy Version 0.9-RC2) tool issue - pending fix, then update main to latest in MTS

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#105]
These errors look like dependency problems. Could we check?

Tool ID | toolshed.g2.bx.psu.edu/repos/iuc/circos/circgraph/0.9-RC2
Tool Version | 0.9-RC2

Test history: https://usegalaxy.org/u/jen/h/test-history-circos

Examples, I could be using it wrong, but it looks like if anything other than the baseline karyotype input is added in, the tool fails.

**dataset 15**

<img width="924" alt="screen shot 2018-03-21 at 10 42 50 am" src="https://user-images.githubusercontent.com/8999735/37727341-cee057ca-2cf4-11e8-8dfd-e84b36b9cf0f.png">

<img width="851" alt="screen shot 2018-03-21 at 10 43 07 am" src="https://user-images.githubusercontent.com/8999735/37727342-cefc24fa-2cf4-11e8-9fea-c24f61afd949.png">

**dataset 22**

<img width="771" alt="screen shot 2018-03-21 at 10 41 42 am" src="https://user-images.githubusercontent.com/8999735/37727329-c9297cf8-2cf4-11e8-963b-becc965a87fc.png">

**Mismatched inputs are also a problem and could be handled better, but that issue is for the tool developers to address:**

dataset 9

<img width="696" alt="screen shot 2018-03-21 at 10 51 45 am" src="https://user-images.githubusercontent.com/8999735/37727880-1b4f6bd6-2cf6-11e8-937b-0a6acd802d65.png">

@natefoo @davebx

**Comment by erasche** [comment]
I'll look into these over the next week. These are all likely tool problems.

**Comment by erasche** [comment]
(Alternate explanation: this is why it's RC2? Now maybe we'll get a 1.0 out of it that there's more real-world testing.)

**Comment by jennaj** [comment]
Retesting. The HISAT2 link in was wrong (and has been removed)

**Comment by jennaj** [comment]
Failed retest, still needs a fix

**Comment by jennaj** [comment]
Created ticket at IUC repo since it is tool bug. This ticket is now for tracking that fix back to .org (once done).

https://github.com/galaxyproject/tools-iuc/issues/1919

**Comment by erasche** [comment]
Yeah, we still haven't patched it, I'm awful sorry. it's been a busy month unfortunately. The usegalaxy.eu server is feeling a bit more stable for the moment so maybe I can find time to do it.

**Comment by jennaj** [comment]
This version was resolved a while ago. Closing
