### ISSUE TITLE
Update BWA and BWA-MEM on main

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#106]
Might address this usage enhancement already: https://github.com/galaxyproject/tools-iuc/issues/1785

MTS: https://toolshed.g2.bx.psu.edu/view/devteam/bwa/4f774c1e6049

The version on main (both): 0.7.15.1

MTS versions: BWA 0.7.17.4, BWA-MEM 0.7.17.1

**Comment by martenson** [comment]
updated on Main in https://github.com/galaxyproject/usegalaxy-playbook/commit/34a4dd4815981e23ec7f3a436048cf990c3146ce

**Comment by jennaj** [comment]
Tool version (Galaxy Version 0.7.17.4) for both. Initial tests pass. More tests, with a variety of inputs, are in progress. Includes using a custom genome and inputting interleaved/BAM. 

**I'll close this out once all complete, to make sure basic functionality in place.**

Test history: https://usegalaxy.org/u/jen/h/test-history-bwa-mem-paired-interleaved-interlaced (includes other tests -- ignore those -- updated tool tests are in datasets 13-17.

For reference, enhancements for these tools have been submitted to the IUC to address the differences between the two tools and accepted inputs. Graphics in 1785 show what is going on.

 - https://github.com/galaxyproject/tools-iuc/issues/1785
 - https://github.com/galaxyproject/tools-iuc/issues/1799

**Comment by jennaj** [comment]
Tests pass, closing, thanks!

BWA included with PR https://github.com/galaxyproject/usegalaxy-playbook/commit/34a4dd4815981e23ec7f3a436048cf990c3146ce
