### ISSUE TITLE
Tools failing with perl dependency problem

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#111]
**For end-users: The workaround is to use the tool at the Galaxy Europe mirror at https://usegalaxy.eu/**

ping @davebx @natefoo 

Perl module missing/not found at Galaxy Main https://usegalaxy.org. This is new within the last week or so:

**Barcode splitter**

> Can't locate Data/Dumper.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /galaxy/main/deps/fastx_toolkit/0.0.13/devteam/package_fastx_toolkit_0_0_13/ec66ae4c269b/bin/fastx_barcode_splitter.pl line 22.
> BEGIN failed--compilation aborted at /galaxy/main/deps/fastx_toolkit/0.0.13/devteam/package_fastx_toolkit_0_0_13/ec66ae4c269b/bin/fastx_barcode_splitter.pl line 22.

Version installed at main: https://toolshed.g2.bx.psu.edu/view/devteam/fastx_barcode_splitter/8abdedf55101

An updated version is available: https://toolshed.g2.bx.psu.edu/view/lparsons/fastx_barcode_splitter_enhanced/0fb7e9130a70

**Comment by jennaj** [comment]
Another tool found with the problem. There could be more. 

**Annotate VCF**

> Log: tool progress
> Can't locate Data/Dumper.pm in @INC (@INC contains: /galaxy/main/deps/vcftools/0.1.11/devteam/package_vcftools_0_1_11/710efaae2ff8/vcftools/lib/perl5/site_perl /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /galaxy/main/deps/vcftools/0.1.11/devteam/package_vcftools_0_1_11/710efaae2ff8/vcftools/lib/perl5/site_perl/Vcf.pm line 75.
> BEGIN failed--compilation aborted at /galaxy/main/deps/vcftools/0.1.11/devteam/package_vcftools_0_1_11/710efaae2ff8/vcftools/lib/perl5/site_perl/Vcf.pm line 75.
> Compilation failed in require at /galaxy/main/deps/vcftools/0.1.11/devteam/package_vcftools_0_1_11/710efaae2ff8/vcftools/bin/vcf-annotate line 9.
> BEGIN failed--compilation aborted at /galaxy/main/deps/vcftools/0.1.11/devteam/package_vcftools_0_1_11/710efaae2ff8/vcftools/bin/vcf-annotate line 9.

Version installed at main:
https://toolshed.g2.bx.psu.edu/view/devteam/vcftools_annotate/57a6550df582

**Comment by MurphyDavid** [comment]
minor note: The suggested workaround of using usegalaxy.eu doesn't work for people hitting this error for the annovar tool since it isn't installed on usegalaxy.eu

`Following tools missing: [u'toolshed.g2.bx.psu.edu/repos/devteam/table_annovar/table_annovar/0.2']`

**Comment by natefoo** [comment]
These tools should be working again, I've installed `Data::Dumper` module on our nodes in galaxyproject/infrastructure-playbook@f4186c1ab8ea0414a875247bfe59d9aa84bd6f9e. It must have been installed on the nodes back when they were running CentOS 6, but was not installed when we upgraded them.

I initially installed it in to the `package_fastx_toolkit_0_0_13` dependency dir, and while that worked, I decided to search for other tools that use `Data::Dumper`. And there are a **lot** of them, so installing the system package is the only feasible solution.

**Comment by jennaj** [comment]
Thanks @natefoo  - tests in progress 

@MurphyDavid good point - yes, all installed tools are not aligned across the new Galaxy mirrors (yet, soon will be). If you also want to test run Annovar now after the fix (back at usegalaxy.org), feedback about the result would be great.

**Comment by jennaj** [comment]
Tools are finding the dependency now at usegalaxy.org. Thanks & closing out!
