### ISSUE TITLE
Upload tool is problematically stating that fastqsanger.gz input is not to spec (when data is)

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#115]
New in 18.05 pre-release. This is tutorial data and it works fine with tools/checks out with FastQC and when autodetect is used instead at Upload.

Test history: https://usegalaxy.org/u/jen/h/test-history-trimmomatic-trim-galore

Datasets 9 + 10 were downloaded to retest all this.

Data compressed (mac gzip), then re-uploaded:

 - into datasets 17 + 18 (assigned fastqsanger.gz at Upload) - compression remains but there is an odd warning (@martenson agrees this is an 18.05 bug)
<img width="249" alt="screen shot 2018-05-07 at 12 00 50 pm" src="https://user-images.githubusercontent.com/8999735/39719615-9a8ef160-51ee-11e8-956c-66ddf5f44571.png">

 
 - into datasets 57 + 58 (autodetect used at Upload) - uncompressed and assigned fastqsanger (correct)

Same data uncompressed (mac gunzip), then re-uploaded:

 - into datasets 59 + 60 (autodetect used at Upload) - assigned fastqsanger (correct)

**Comment by martenson** [comment]
xref https://github.com/galaxyproject/galaxy/issues/6074

**Comment by jennaj** [comment]
Retesting on main

**Comment by jennaj** [comment]
Same test history

datasets 61 & 62, fastqsanger.gz, autodetect in upload, no warning now. Fixed!

datasets 63 & 64, fastqsanger.gz, datatype assigned in upload, no warning now. Fixed!
