### ISSUE TITLE
Bedtools: BAM Filter fails with any rule combination, including those in tool help

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#116]
**Tool version:** toolshed.g2.bx.psu.edu/repos/devteam/bamtools_filter/bamFilter/2.4.1

Earlier versions of the tool work fine. Is this an 18.05 problem or a tool problem?

**Test history:** https://usegalaxy.org/u/jen/h/test-history-filter-bam-datasets-on-a-variety-of-attributes-galaxy-version-241

Not tested at usegalaxy.eu (BamTools is not installed)

**Error:**

```
Traceback (most recent call last):
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/jobs/runners/__init__.py", line 191, in prepare_job
    job_wrapper.prepare()
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/jobs/__init__.py", line 865, in prepare
    self.command_line, self.extra_filenames, self.environment_variables = tool_evaluator.build()
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/tools/evaluation.py", line 435, in build
    raise e
TypeError: <galaxy.tools.wrappers.InputValueWrapper object at 0x7f2929ada2d0> is not JSON serializable
```

**Comment by jennaj** [comment]
Update: The selects for inputs with this tools are behaving strangely. What is chosen on the tool form is not always what is submitted to the tool (flips back to default selection before the user makes a choice). 

Found this during initial testing, not retested yet under the most recent update for pre-release 18.05 on main. Has been reported at Biostars again today. Will test again. Would this need a distinct ticket?

**Comment by jennaj** [comment]
Still a problem with (Galaxy Version 2.4.1). When corrected, please change the label back to retest.

**Comment by natefoo** [comment]
The object that it's trying to serialize is [$rule_configuration.rules](https://github.com/galaxyproject/tools-iuc/blob/5f8052ab47b789da5ea47feb48e1b8e08b5fc1e0/tool_collections/bamtools/bamtools_filter/bamtools-filter.xml#L30). I believe this can be fixed by changing it to:

```
        #set $config[ 'rule' ] = str($rule_configuration.rules)
```

It allows the tool to run locally for me, although I can't verify the results. @davebx does this change make sense to you?

**Comment by davebx** [comment]
@natefoo yeah, that looks reasonable. I do wonder why (or whether) it worked before, without casting to string.

**Comment by natefoo** [comment]
I created a PR at galaxyproject/tools-iuc#1922.

**Comment by natefoo** [comment]
The tool's been updated on Main and the job in the test history runs successfully for me now.
