### ISSUE TITLE
Update htseq_count to version 0.9.1 on Main to fix a bug - original bug fixed, new one introduced in solution, no updated tool revision (yet)

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#124]
Fixes a bug where the tool always produced the BAM output. When it is empty, shows up in the history with a metadata problem (cannot be indexed).

 I noticed the empty BAM from this tool before (and with other tools) but didn't know it could be triggered by this tool option bug with htseq. Empty BAMs are not entirely uncommon and could still be produced by this tool if the user doesn't exclude the BAM output specifically.

How to better handle empty BAMs -- globally -- is a different question/solution.

HTseq Fix: https://github.com/galaxyproject/tools-iuc/pull/1857/files
MTS: https://toolshed.g2.bx.psu.edu/view/lparsons/htseq_count/7f5a8d427b39
Gitter: https://gitter.im/galaxyproject/Lobby?at=5af9cbdae1cf621dba1bb3d7

ping @martenson @davebx

**Comment by davebx** [comment]
I've updated htseq-count to 26:7f5a8d427b39, the most recent revision available on main toolshed.

**Comment by jennaj** [comment]
Great, thanks - retesting

**Comment by jennaj** [comment]
The original item is fixed (BAMs are not produced when not set as output). Dataset 95 + 96 in this test history: https://usegalaxy.org/u/jen/h/test-history-star-hisat2-featurecounts-htseq-deseq2-better

But the genome select pull-down is not working for this tool when a BAM is requested under advanced options. The fix needs to be made, the tool updated in MTS, then reinstalled again. Tested at both org and eu - is a tool problem.

Ticket with details: https://github.com/galaxyproject/tools-iuc/issues/1918

**Comment by jennaj** [comment]
Let's close this one out since the big issue was fixed with the update.

Made another ticket to track an update for the that IUC bug fix. Is minor. https://github.com/galaxyproject/usegalaxy-playbook/issues/138
