### ISSUE TITLE
"selected" datasets are not always what is submitted to the job

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#125]
Test history: https://usegalaxy.org/u/jen/h/test-history-concatenate-fastq

Compare datasets 18 & 19 -- 18 was run directly from the tool panel, 19 was a "rerun" of that job with the selected items changed back to what was originally selected with 18 but not picked up. 

For 18, the job details show that the same dataset was input to the tool multiple times -- the default selection when the tool is first brought up. That same test history has multiple examples of the selected dataset not being input - any job details with a repeated-input is one of those that had a problem.

Users have reported this problem with other tools with selects structured like this tools (Cuffdiff is one example). 

UI problem?

ping @dannon

**Comment by jennaj** [comment]
Biostars question about the same issue with Cuffdiff: https://biostar.usegalaxy.org/p/28036/

**Comment by martenson** [comment]
this should be fixed,please retest

**Comment by jennaj** [comment]
Tests pass, cannot reproduce with direct runs or reruns. Thanks & closing!!
