### ISSUE TITLE
Cannot queue more files to load with Upload when another file is still processing

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#126]
@guerler @dannon This might be related to 18.05. Just found it while doing other tests.

How to reproduce:

Upload a file that takes a bit longer to process. Note that while that is processing (in upload tool), the buttons to start another upload are greyed out (not usable). As soon as the first file finishes queueing, then the buttons are active again.

<img width="890" alt="screen shot 2018-05-17 at 9 01 44 am" src="https://user-images.githubusercontent.com/8999735/40189657-d85e8878-59b1-11e8-9791-1766bb423e3d.png">

<img width="892" alt="screen shot 2018-05-17 at 9 03 05 am" src="https://user-images.githubusercontent.com/8999735/40189659-d8794140-59b1-11e8-9b9a-f3264eace0ed.png">

**Comment by jennaj** [comment]
@martenson should this have gone under the /galaxy repo instead? I don't see an issue/PR for this but maybe missed it. I wasn't sure if just a main problem or a new 18.05 bug with Upload.

I can create a new ticket at /galaxy and link it back if still undergoing review (no PR yet). This seems important, many will notice the change in functionality. When this occurs, you cannot navigate away from the history or load more data -- just have to wait it out -- seems problematic,

**Comment by martenson** [comment]
@jennaj If I understand it correctly this could be a Galaxy bug related to chunked uploads and should be in /galaxy repo.

**Comment by martenson** [comment]
moved to galaxy proper
