### ISSUE TITLE
Update Diffbind to version 2.6.6.2 (currently at 2.6.5.0)

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#127]
Should fix memory issues with usage. Test once updated.

https://github.com/galaxyproject/tools-iuc/pull/1768

**Comment by jennaj** [comment]
The tool form is very different and I think I used it correctly. Earlier tool versions worked with the same input, so don't think content is a factor. @nekrut If you have time, could you check to see if I am using the tool incorrectly? Thanks!

Test history: https://usegalaxy.org/u/jen/h/test-history-diffbind

Data 25 is the test and has this **stderr in a green dataset**

`ln: target ‘BED_-peaks.bed’ is not a directory`

**Comment by natefoo** [comment]
It looks like it's creating symlinks based on the input dataset names:

```console
ln -s '/galaxy-repl/main/files/019/888/dataset_19888521.dat' One-uninj rep2_MACS2 callpeak on data 17 and data 19 _summits in BED_-peaks.bed && \
ln -s '/galaxy-repl/main/files/019/859/dataset_19859441.dat' Bowtie2 on data 15_ aligned reads _sorted BAM_-bamreads.bam && \\
ln -s /galaxy-repl/main/files/_metadata_files/001/399/metadata_1399910.dat Bowtie2 on data 15_ aligned reads _sorted BAM_-bamreads.bai && \
ln -s '/galaxy-repl/main/files/019/859/dataset_19859439.dat' One-Bowtie2 on data 13_ aligned reads _sorted BAM_-bamcontrol.bam && \
ln -s /galaxy-repl/main/files/_metadata_files/001/399/metadata_1399908.dat One-Bowtie2 on data 13_ aligned reads _sorted BAM_-bamcontrol.bai && \
ln -s '/galaxy-repl/main/files/019/888/dataset_19888555.dat' Two-uninj rep3_MACS2 callpeak on data 17 and data 20 _summits in BED_-peaks.bed && \
ln -s '/galaxy-repl/main/files/019/859/dataset_19859442.dat' Bowtie2 on data 16_ aligned reads _sorted BAM_-bamreads.bam && \
ln -s /galaxy-repl/main/files/_metadata_files/001/399/metadata_1399915.dat Bowtie2 on data 16_ aligned reads _sorted BAM_-bamreads.bai && \
ln -s '/galaxy-repl/main/files/019/859/dataset_19859439.dat' Two-Bowtie2 on data 13_ aligned reads _sorted BAM_-bamcontrol.bam && \
ln -s /galaxy-repl/main/files/_metadata_files/001/399/metadata_1399908.dat Two-Bowtie2 on data 13_ aligned reads _sorted BAM_-bamcontrol.bai
```

It [tries to perform a replace for a few invalid characters](https://github.com/galaxyproject/tools-iuc/blob/5f8052ab47b789da5ea47feb48e1b8e08b5fc1e0/tools/diffbind/diffbind.xml#L40) but it doesn't look like it's working right.

@mblue9 is there a reason that these need to have a filename that resembles the input dataset? It'd be possible for someone to create a name that would cause the tool to do something insecure and catching all those possible cases would be tricky. Instead, can it just use relatively standard names, e.g.: `${g.index}-peaks-${i}.bed` where `$i` is the index of the peaks loop (I am not sure if there's a way to get a repeat group list index as in `$g.index` because I don't write tools but presumably there's something like this). Also those link names should probably be wrapped in double quotes since they use user input?

**Comment by blankenberg** [comment]
In the very least should have single quotes around the filename during linking, and remove/replace any single quotes in the during generation.

Can always use `enumerate()` with any iterable to get an index.

**Comment by natefoo** [comment]
The following allows the tool to run for me (locally):

```patch
diff -r 1de83981d43c diffbind.xml
--- a/diffbind.xml	Wed May 30 12:25:42 2018 -0400
+++ b/diffbind.xml	Tue Jun 05 15:40:40 2018 -0400
@@ -30,23 +30,23 @@
 #set $temp_factor_names = list()
 #set $temp_factor = list()
 
-#for $g in $rep_group:
+#for $gi, $g in enumerate($rep_group):
 
     #set $peak_files = list()
     #set $bam_files = list()
     #set $bam_controls = list()
 
-    #for $file in $g.peaks:
-        #set $file_name = re.sub('[^\w\-\s]', '_', str($file.element_identifier))
-        ln -s '${file}' ${g.groupName}-${file_name}-peaks.bed &&
-        $peak_files.append(str($g.groupName) + '-' + $file_name + '-peaks.bed')
+    #for $i, $file in enumerate($g.peaks):
+        #set $file_name = 'group' + str($gi) + '-peaks' + str($i) + '.bed'
+        ln -s '${file}' '${file_name}' &&
+        $peak_files.append($file_name)
     #end for
 
-    #for $bam in $g.bamreads:
-        #set $bam_name = re.sub('[^\w\-\s]', '_', str($bam.element_identifier))
-        ln -s '${bam}' ${bam_name}-bamreads.bam &&
-        ln -s ${bam.metadata.bam_index} ${bam_name}-bamreads.bai &&
-        $bam_files.append($bam_name + '-bamreads.bam')
+    #for $i, $bam in enumerate($g.bamreads):
+        #set $bam_name = 'group' + str($gi) + '-bamreads' + str($i)
+        ln -s '${bam}' '${bam_name}.bam' &&
+        ln -s '${bam.metadata.bam_index}' '${bam_name}.bai' &&
+        $bam_files.append($bam_name + '.bam')
     #end for
 
     $temp_factor.append( {str($g.groupName): $peak_files} )
@@ -54,10 +54,10 @@
 
     #if str( $g.bamcontrol ) != 'None':
         #for $ctrl in $g.bamcontrol:
-            #set $ctrl_name = re.sub('[^\w\-\s]', '_', str($ctrl.element_identifier))
-            ln -s '${ctrl}' ${g.groupName}-${ctrl_name}-bamcontrol.bam &&
-            ln -s ${ctrl.metadata.bam_index} ${g.groupName}-${ctrl_name}-bamcontrol.bai &&
-            $bam_controls.append(str($g.groupName) + '-' + $ctrl_name + '-bamcontrol.bam')
+            #set $ctrl_name = 'group' + str($gi) + '-bamcontrol' + str($i)
+            ln -s '${ctrl}' '${ctrl_name}.bam' &&
+            ln -s '${ctrl.metadata.bam_index}' '${ctrl_name}.bai' &&
+            $bam_controls.append($bam_name + '.bam')
         #end for
         $temp_factor.append( {str($g.groupName): $bam_controls} )
     #end if
```

But results in the following error:

```
Fatal error: An undefined error occured, please check your input carefully and contact your administrator.
Warning: namespace ‘RMySQL’ is not available and has been replaced
by .GlobalEnv when processing object ‘collapse’
Warning: namespace ‘RMySQL’ is not available and has been replaced
by .GlobalEnv when processing object ‘collapse’
Warning: namespace ‘RMySQL’ is not available and has been replaced
by .GlobalEnv when processing object ‘collapse’
Warning: namespace ‘RMySQL’ is not available and has been replaced
by .GlobalEnv when processing object ‘collapse’
Error in `$<-.data.frame`(`*tmp*`, SampleID, value = c(1L, 0L)) : 
  replacement has 2 rows, data has 0
Calls: dba -> pv.model -> $<- -> $<-.data.frame
```

Not sure if that is an issue with the data or my fix.

**Comment by mblue9** [comment]
@natefoo thanks for the notification about this!

Your changes work if you change the hacky way I assign the peak and bam files. In the diffbind.R file change to what you're now using as filenames e.g.
```
peaks <- filenamesIn[grepl("peaks", filenamesIn)]
bams <- filenamesIn[grepl("bamreads.*bam", filenamesIn)]
ctrls <- filenamesIn[grepl("bamcontrol.*bam", filenamesIn)]
```

But 

>@mblue9 is there a reason that these need to have a filename that resembles the input dataset?

Yes.

As currently with diffbind 2.6.6.3 the user gets (for the main output):
```
Chrom	Start	End	Name	Score	Strand	Conc	Conc_Responsive	Conc_Resistant	Fold	p.value	FDR
chr18	394599	396513	DiffBind	0	.	7.15	5.55	7.89	-2.35	7.06e-24	9.84e-21
chr18	111566	112005	DiffBind	0	.	5.71	6.53	3.63	2.89	1.27e-08	8.88e-06
```
and if the changes proposed here were added the user instead would get:
```
Chrom	Start	End	Name	Score	Strand	Conc	Conc_group1	Conc_group0	Fold	p.value	FDR
chr18	394599	396513	DiffBind	0	.	7.15	5.55	7.89	-2.35	7.06e-24	9.84e-21
chr18	111566	112005	DiffBind	0	.	5.71	6.53	3.63	2.89	1.27e-08	8.88e-06
```

i.e. they lose the informative group names

And for the binding matrix output, currently with diffbind 2.6.6.3 the user gets:
```
Chrom	Start	End	MCF7_ER_1_bed_gz	MCF7_ER_2_bed_gz	BT474_ER_1_bed_gz	BT474_ER_2_bed_gz
chr18	111566	112005	137.615208000375	59.878372946728	29.4139375878664	19.9594576489093
chr18	189222	189652	19.9594576489093	12.6059732519427	11.5554754809475	23.110950961895
```

and if the changes proposed here were added the user would get instead:
```
Chrom	Start	End	peaks0.bed	peaks1.bed	peaks0.bed.1	peaks1.bed.1
chr18	111566	112005	137.615208000375	59.878372946728	29.4139375878664	19.9594576489093
chr18	189222	189652	19.9594576489093	12.6059732519427	11.5554754809475	23.110950961895
```
i.e. they lose the sample names, which is not very helpful I think, as imo it would be potentially confusing, error-prone and unnecessary extra hassle for the users to rename.

I've attempted to fix the issue by replacing the spaces in the element_identifier and adding quotes here: https://github.com/galaxyproject/tools-iuc/pull/1923.

But Jen, what you're testing with Dataset 25 in your history won't work anyway, as diffbind needs 4 samples minimum, 2 for each group, you've only got 1 in each group in that case. I did put that in the Help section but I've now made it bold.

**Comment by natefoo** [comment]
@mblue9 Thanks! Running your patch the filenames are valid, although it fails if the same control BAM is used for both groups because it tries to create the same symlink twice:

```
ln: failed to create symbolic link 'Bowtie2_on_data_13__aligned_reads__sorted_BAM_-bamcontrol.bam': File exists
```

@blankenberg I double checked, Galaxy is already converting other "dangerous" characters like `/` and `'`.

**Comment by mblue9** [comment]
@natefoo I'm not sure how to fix that control file issue but I'll try to take a look asap. Fwiw it's actually recommended by the diffbind authors to not use control BAMs at this step, but to use them upstream at the peak calling step (I put that in the help).

Thanks for checking the dangerous characters! That's good to know that the other ones are taken care of by Galaxy. I don't know if it's possible, but I think it would be great if we could use a "safe" element_identifier, where all dangerous characters and things that can lead to issues (e.g. spaces) are replaced/handled behind the scenes by Galaxy, so it's quicker to wrap these tools, and to give more consistency in how people are using the element_identifier (I've used a few different ways now I think e.g. +/- spaces).

**Comment by mblue9** [comment]
I've added a fix for that control file issue now here: https://github.com/galaxyproject/tools-iuc/pull/1923

**Comment by natefoo** [comment]
Thanks @mblue9! Installing this now.

**Comment by natefoo** [comment]
Installed in 703b5c1fd336456ac03643671dca27b2b9e8d5dc

**Comment by jennaj** [comment]
Test failed, same test history, data 26. Also send that in as a bug report. 

I expected no contrasts with this dinky test, so ignore those warnings. 

Problem is with the "RMySQL" namespace, yes?


```Dataset Error
An error occured while running the tool toolshed.g2.bx.psu.edu/repos/bgruening/diffbind/diffbind/2.6.6.4.

Tool execution generated the following messages:

Fatal error: An undefined error occured, please check your input carefully and contact your administrator.
Warning: namespace ‘RMySQL’ is not available and has been replaced
by .GlobalEnv when processing object ‘collapse’
Warning: namespace ‘RMySQL’ is not available and has been replaced
by .GlobalEnv when processing object ‘collapse’
Warning: namespace ‘RMySQL’ is not available and has been replaced
by .GlobalEnv when processing object ‘collapse’
Warning: namespace ‘RMySQL’ is not available and has been replaced
by .GlobalEnv when processing object ‘collapse’
uninj_rep2_MACS2_callpeak_on_data_17_and_data_19__summits_in_BED_ uninj_rep2_MACS2_callpeak_on_data_17_and_data_19__summits_in_BED_  Two  NA raw
control_peaks_1 control_peaks_1  One  NA raw
Warning message:
No contrasts added. Perhaps try more categories, or lower value for minMembers. 
Error in pv.DBA(DBA, method, bSubControl, bFullLibrarySize, bTagwise = bTagwise,  : 
  Unable to perform analysis: no contrasts specified.
Calls: dba.analyze -> pv.DBA
Warning message:
No contrasts added. Perhaps try more categories, or lower value for minMembers. 
```

This job did not have that output set to yes in advanced options (Output RData file?) but that may not matter for the core calculation. 

Another test going in 27 that might produce contrasts, I'll run something different (full test) if that doesn't clean up the stderr so we have a clean test.

**Comment by jennaj** [comment]
Ok, just read through comments, a full test is needed. On it.

**Comment by jennaj** [comment]
Ok, set up a proper test history. Uses latest tool version for MAC2 and Diffbind 2.6.6.4. Inherited training data bam that used some older version of Bowtie2/hg18 but that should not impact test. 

Used all default options (no extra outputs, etc) to get a baseline.

Test history: https://usegalaxy.org:/u/jen/h/test-history-bowtie2-macs2-diffbind (*executing*)

MACS2 && Diffbind both using controls (NOT recommended usage): Data 17

MACS2 using controls, Diffbind no controls (recommended usage): Data 18

**Comment by jennaj** [comment]
I can't get a successful run with this data unless I significantly change the runtime params. This looks like a data issue, not tool. Closing out as functional.

I need a good Diffbind test case -- @mblue9 do you have one that you'd be willing to share (and have it be public)? Ping me directly in Gitter if yes. I can mask/reduce any shared data to make it more "test-case" friendly if you just have full-size data right now. We don't have data like this for the GTN tutorials yet -- could be a start. Or maybe I should use the sample data from here... http://bioconductor.org/packages/release/bioc/vignettes/DiffBind/inst/doc/DiffBind.pdf

**Comment by jasonsaunderswilliams** [comment]
Hi guys, I'm using DiffBind on usegalaxy.eu version 2.6.6.1. I have tried with and without inputs, our ChIP seq pipeline uses the inputs to generate the .bed peak files anyway. I get this error:
"[1] "en_US.UTF-8"
Warning: namespace ‘RMySQL’ is not available and has been replaced
by .GlobalEnv when processing object ‘collapse’
Warning: namespace ‘RMySQL’ is not available and has been replaced
by .GlobalEnv when processing object ‘collapse’
Warning "

I have tried using other versions but I still get errors. Any help would be appreciated:
**Dataset Error**
An error occurred while running the tool toolshed.g2.bx.psu.edu/repos/bgruening/diffbind/diffbind/2.6.6.1.

Error Details
Execution resulted in the following messages:

Fatal error: An undefined error occured, please check your intput carefully and contact your administrator.
Tool generated the following standard error:

Warning: namespace ‘RMySQL’ is not available and has been replaced
by .GlobalEnv when processing object ‘collapse’
Warning: namespace ‘RMySQL’ is not available and has been replaced
by .GlobalEnv when processing object ‘collapse’
Warning: namespace ‘RMySQL’ is not available and has been replaced
by .GlobalEnv when processing object ‘collapse’
Warning: namespace ‘RMySQL’ is not available and has been replaced
by .GlobalEnv when processing object ‘collapse’
2_059E_00OLSwansea_CS001_H3K4me3_hs_i86_trim_bowtie2UPBlkLstRm_MACS_peaks_bed 2_059E_00OLSwansea_CS001_H3K4me3_hs_i86_trim_bowtie2UPBlkLstRm_MACS_peaks_bed  CV1  NA raw
A_ENCFF162UDQ_H3K4Me3_MACS_peaks_bed A_ENCFF162UDQ_H3K4Me3_MACS_peaks_bed  Con  NA raw
Warning messages:
1: In message(as.character(samples$SampleID[i]), " ", as.character(samples$Tissue[i]),  :
  NAs introduced by coercion
2: In cbind(NULL, c(sampID, tissue, factor, condition, consensus, peak.caller,  :
  NAs introduced by coercion
3: In message(as.character(samples$SampleID[i]), " ", as.character(samples$Tissue[i]),  :
  NAs introduced by coercion
4: In cbind(NULL, c(sampID, tissue, factor, condition, consensus, peak.caller,  :
  NAs introduced by coercion
Warning message:
No contrasts added. Perhaps try more categories, or lower value for minMembers. 
Error in pv.DBA(DBA, method, bSubControl, bFullLibrarySize, bTagwise = bTagwise,  : 
  Unable to perform analysis: no contrasts specified.
Calls: dba.analyze -> pv.DBA
Warning message:
No contrasts added. Perhaps try more categories, or lower value for minMembers. 

Thank you in advance,

Best,

Jason

**Comment by mblue9** [comment]
The first error is just a warning afaik and should be fixed with this PR https://github.com/galaxyproject/tools-iuc/pull/2481#discussion_r300597371

The main error seems to be that contrasts haven’t been specified, have you added names for the 2 groups into the tool form?

**Comment by jasonsaunderswilliams** [comment]
Hi @mblue9 , I will make sure that I do name the groups if indeed I forgot this time.

I'm sorry, I'm new to galaxy. I don't know what a PR is or how to implement it.

Are you referring to this:

galaxyproject:master←mblue9:diffbind_2.10.0

If so, how do I implement this change in my galaxy tool?

Sorry if this is a basic question.

Cheers,

Jason

**Comment by jennaj** [comment]
@jennaj Retest this at usegalaxy.org

**Comment by jasonsaunderswilliams** [comment]
Hi Jennifer,

Thanks.

Which version should I run to re-test on usegalaxy.org?

Best,

Jason


________________________________

**Comment by jennaj** [comment]
Hi Jason, the current version is:

DiffBind differential binding analysis of ChIP-Seq peak data (Galaxy Version 2.6.6.4)

My comment was a "note to self" to re-integration test the tool .. will probably get to it this week. But please go ahead and try the updated tool out. If you have problems, send in a bug report and put a link to this issue in the comments so I can find it, then ping me here so I know when to look for it. It is works, that feedback would be great, too :)

**Comment by jasonsaunderswilliams** [comment]
Thanks Jennifer,

On my usegalaxy.org, the latest version is 2.6.5.0?

Best wishes,

Jason

________________________________

**Comment by jennaj** [comment]
@jasonsaunderswilliams 

Hi -- if working at Galaxy Main https://usegalaxy.org, the most current tool version is `2.6.6.4`.

If the older version of the tool is loading with the "rerun" icon, click on the "Versions" menu to switch to the newer version. The new form will attempt to inherit data/settings from the original run -- but double check those before executing the job.

The newer version will load from the left tool panel, but that starts over with a brand new form (whatever data/setting from an earlier run wouldn't be populated the same way as a "rerun" would). This can sometimes be a good thing and is what I'll be doing.

I haven't tested yet, but it is still on my to-do list for this week. The downsampled input test data I'll be using is the history shared from @mblue9 above. Is currently at usegalaxy.eu. Moving it over to usegalaxy.org is part of the test prep. Moving history archives from EU > ORG was a bit problematic ~two weeks ago, but might be better now. So, is also part of a larger test for that functionality fix. There is a ticket for that issue .. will link it all together when I start this up.

**Comment by jennaj** [comment]
@jasonsaunderswilliams

Turns out the test for version `2.6.6.4` was already done. I reran the test just to confirm there isn't a new problem (there isn't). Test history: https://usegalaxy.org:/u/jen/h/testing-diffbind-from-mblue9

There are no problems with viewing PDF plots. Maybe compare your methods with this example test?You should also make sure to run Galaxy at the most current version `19.05` and the tool at the most current version `2.6.6.4`.
