### ISSUE TITLE
Update FastQC from v 0.69 to v 0.72 once in MTS

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#129]
0.71  is the most current in the MTS (updated 1/2018)

https://toolshed.g2.bx.psu.edu/view/devteam/fastqc/ff9530579d1f

**Comment by jennaj** [comment]
v 0.72 is being released: https://github.com/galaxyproject/tools-iuc/pull/1913/files

When in MTS and ready to install, the tool will also need to be added to the whitelist.

ping @davebx @natefoo

**Comment by natefoo** [comment]
I whitelisted it.
