### ISSUE TITLE
Update RNA STAR 2.5.2b-0 (database assignment fix)

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#134]
Not PR'd yet, can link back in once done.

Details: https://github.com/galaxyproject/usegalaxy-playbook/issues/104#issuecomment-395083588

**Comment by martenson** [comment]
> Not PR'd yet, can link back in once done.

@jennaj What does this mean?

**Comment by natefoo** [comment]
@martenson see the linked comment, this tool needs to be updated in the same way as HISAT2 in galaxyproject/tools-iuc#1902.

**Comment by jennaj** [comment]
It means that either no one has fixed the tool yet via PR or that it exists, but wasn't linked back to the master ticket #104 yet (the way that HISAT2 was)

**Comment by jennaj** [comment]
And Bowtie2 now as well. Missed that the log wasn't getting the correct database in earlier tests. See https://github.com/galaxyproject/usegalaxy-playbook/issues/104#issuecomment-395083588

Made an update ticket for Bowtie2 as well, linked from the above

**Comment by martenson** [comment]
I see, so this is a ticket to track updating to a version that will be created once the bug is fixed, thanks for explaining.

**Comment by natefoo** [comment]
PR'd at galaxyproject/tools-iuc#1929.

**Comment by davebx** [comment]
Installed on test and main in 1b5edc4e15bcbd5db7e8774e0a5504413c365f5a

**Comment by jennaj** [comment]
Tests pass https://usegalaxy.org/u/jen/h/test-history-mappers

dataset 133-146

Thanks!
