### ISSUE TITLE
Update Bowtie2 2.3.4.1 (database assignment fix)

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#135]
Not PR'd yet, can link back in once done.

Details: #104 (comment)

**Comment by natefoo** [comment]
PR'd galaxyproject/tools-iuc#1927

**Comment by jennaj** [comment]
@natefoo thank you for PR, @blankenberg thanks for fix!

@davebx or @martenson  Is in the MTS now and ready to have the update installed at main, version 2.3.4.2

**Comment by natefoo** [comment]
Installed 2.3.4.2 in 703b5c1fd336456ac03643671dca27b2b9e8d5dc

**Comment by jennaj** [comment]
Passes tests data 127-132 in here https://usegalaxy.org/u/jen/h/test-history-mappers

Closing & thanks!
