### ISSUE TITLE
Update NVC to 0.0.4 on Main

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/usegalaxy-playbook#136]

**Comment by davebx** [comment]
Updated in e118cc1a2487b918444819af42e015f19af75126

**Comment by blankenberg** [comment]
Thanks!

**Comment by jennaj** [comment]
Tested with a dinky dataset and it passed (same result as v 0.0.2). Running a larger test through-- might take a while. Should we close this out?

Test history: https://usegalaxy.org/u/jen/h/test-history-nvc

Positive @blankenberg has better tests. (please share back if can, so I am current)

**Comment by blankenberg** [comment]
The update was successful. If there are other concerns with the tool itself, can make new issues specifically for them.

**Comment by jennaj** [comment]
And it worked on a larger dataset that used to sometimes fail, which is great. Thx!
