### ISSUE TITLE
update Du Novo on Main

### ISSUE THREAD

**Issue by martenson** [galaxyproject/usegalaxy-playbook#137]

**Comment by davebx** [comment]
As far as I can tell, the most recent (10:9dc43bf7d1db) revision of Du Novo was installed in 3ec46d06eb5b4ea551bc835cd920176ff3a8f974

**Comment by martenson** [comment]
looks alright, I blame @NickSto for requesting it without checking

thanks @davebx

**Comment by NickSto** [comment]
Hey @davebx, thanks! Didn't realize you'd gone ahead and done it!
