### ISSUE TITLE
Update Featurecounts once ready (usage fixes)

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#139]
The new change, reverts some of the strictness (might be other fixes/changes): https://github.com/galaxyproject/tools-iuc/pull/1867/commits/42cb8c709549fd2fe8882be18eaa1dffe17474f8

Last update 1.6.0.3 but maybe updated again since then? The functionality changed and was made too strict (required custom build assignments for inputs). https://github.com/galaxyproject/usegalaxy-playbook/issues/52 && https://github.com/galaxyproject/usegalaxy-playbook/issues/86#issuecomment-376715052

Found some issues with the tool when testing DeSeq2. Using htseq instead now for that test. https://github.com/galaxyproject/usegalaxy-playbook/issues/101#issuecomment-384435303

Primary htseq functions ok, one issue with advanced options. https://github.com/galaxyproject/tools-iuc/issues/1918 && https://github.com/galaxyproject/usegalaxy-playbook/issues/138

**Comment by jennaj** [comment]
Galaxy has v Galaxy Version 1.6.2

Lastest in MTS v Galaxy Version 1.6.3

Ready to update to 1.6.3 on main, other issues closed/resolved.

**Comment by jennaj** [comment]
Status == pending update on main, still at v 1.6.2

**Comment by jennaj** [comment]
Status? @davebx

**Comment by davebx** [comment]
Updated to 1.6.3+galaxy2 on usegalaxy.org
