### ISSUE TITLE
Add tool annotateMyIDs to main 

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#141]
MTS: https://toolshed.g2.bx.psu.edu/view/iuc/annotatemyids/9ab35a2245ce

The tool is installed at https://usegalaxy.eu

The tool *UniProt ID mapping and retrieval* can convert many identifiers, but not Entrez gene IDs (output from using FeatureCounts with built-in annotation).

Request through Galaxy Biostars: https://biostar.usegalaxy.org/p/28150

**Comment by jennaj** [comment]
@davebx Tool needs to be added. I don't think it requires any local data files/indexes from reviewing the MTS repo, but once installed I can test that.

**Comment by davebx** [comment]
Installed in https://github.com/galaxyproject/usegalaxy-playbook/commit/9a476008536d522bc34e82816ae82292682797d5

**Comment by jennaj** [comment]
Works! thanks & closing

test histories:

- https://usegalaxy.org:/u/jen/h/test-history-uniprot-annotatemyids
 - https://usegalaxy.eu:/u/jenj/h/test-history-uniprot-annotatemyids
