### ISSUE TITLE
Update Trinity once in MTS to capture a new tool wrapper in the suite

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#143]
PR: https://github.com/galaxyproject/tools-iuc/pull/1937

Related Q&A: https://biostar.usegalaxy.org/p/28312

**Comment by jennaj** [comment]
In progress by @davebx and @natefoo

**Comment by jennaj** [comment]
Trinity itself has been updated and more tools from the suite are in the MTS (and at usegalaxy.eu).

Do we want to add those to main? Can we even use those same versions at main? (not sure) @nekrut @natefoo

**Comment by jennaj** [comment]
Related request from the community (CTAT tools): https://github.com/galaxyproject/usegalaxy-playbook/issues/184

**Comment by jennaj** [comment]
Older ticket left over in galaxy repo (closed out). Punchline: the updated tool is ready to install. https://github.com/galaxyproject/galaxy/issues/4418

**Comment by jennaj** [comment]
Tools are installed but the older version is still present. Both work. Before closing this out -- do we really want both versions available? And in different tool categories? It seems confusing for end-users.

IF we want Trinity under "Assembly" instead of "RNA-seq", then all Trinity/CTAT tools should be moved, so all are kept together. 

Screenshot

<img width="259" alt="trinity-tools-dups-category" src="https://user-images.githubusercontent.com/8999735/74885613-dc6bb700-532a-11ea-9756-53278b867655.png">


ping @natefoo @davebx

**Comment by jennaj** [comment]
per @natefoo -- simply hide the old version and call it done for now. 

who can do this? would be very nice to wrap this up and closeout :)

**Comment by jennaj** [comment]
Updates:
* Trinity has updated to an even newer version. v2.8.5 was tested and passed on Feb 19th. v2.9.1 is the new version tested today, April 3rd.
* All versions of Trinity reliably fail as of a day or so ago with the same error, see below. 
* Not sure why "Detected Common Potential Problems" states that a duplicated dataset was input --- it definitely wasn't.
* The original Trinity tool is still in the tool panel. Not marked as deprecated, in a different tool group, does not thread vs "Version" to the updated wrapper. Hide or tag as deprecated? It is very confusing for end-users, and the old trinity wrapper's output does not play well with the updated Trinity tool suite (there are several downstream tools for filtering, annotation, expression, etc).

Test history, see the top 4 runs for today's tests, bit further down for Feb test. All tagged for context: https://usegalaxy.org/u/jen/h/test-history-trinity

GUI "bug" error reporting view's content below. `srderr` is included. `stdout` from Job Details view is blank (expected). 

> Dataset Error
> An error occurred while running the tool toolshed.g2.bx.psu.edu/repos/iuc/trinity/trinity/2.9.1.
> 
> Error Details
> Tool generated the following standard error:
> 
> code 17: slurm_submit_batch_job error: Invalid account or account/partition combination specified
> 
> Detected Common Potential Problems
> The tool was executed with one or more duplicate input datasets. This frequently results in tool errors due to problematic input choices.

ping @natefoo I know we already discussed and you are working on this. posting to ticket for our tracking and sharing situation with end-users.

**Comment by jennaj** [comment]
**Spades** is reporting the same exact error. No other tools reported as bugs have the same error, and it only started on April 2nd (yesterday). See existing test history for an example.


> Dataset Error
> An error occurred while running the tool toolshed.g2.bx.psu.edu/repos/nml/spades/spades/3.12.0+galaxy1.
> 
> Error Details
> Tool generated the following standard error:
> 
> code 17: slurm_submit_batch_job error: Invalid account or account/partition combination specified
>

**Comment by natefoo** [comment]
The errors were related to cluster upgrades and the exhaustion of our XSEDE credits for Bridges. I have hidden the old version of Trinity and am running a test of the new version, but don't have super high hopes for it because it's going to run on Stampede2 now instead of Bridges until we get a new allocation or supplement.

**Comment by jennaj** [comment]
Resolved!
