### ISSUE TITLE
Trinity 0.0.1 and Unicycler failing immediately on main (PSC Bridges issue)

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#147]
Test history with example, data 88-91: https://usegalaxy.org/u/jen/h/test-history-trinity

ping @natefoo 

```
stderr
code 1: slurm_submit_batch_job: Resource temporarily unavailable
stdout

Job Information
Remote job server indicated a problem running or monitoring this job.
```

**Comment by jennaj** [comment]
Retested today, still fails

**Comment by natefoo** [comment]
Fixed, this was an issue with an incompatibility between slurm-drmaa (compiled by us) and Slurm (installed by PSC) after Slurm was upgraded a couple weeks ago.

**Comment by MarijaDur** [comment]
@natefoo , can you please be so kind to post your solution please... I'm facing the same issue with my galaxy instance.
Thanks,
Marija

**Comment by natefoo** [comment]
@MarijaDur if I recall correctly, the issue was that PSC had upgraded Slurm, which required us to recompile slurm-drmaa for that new version.
