### ISSUE TITLE
Awk installation issue (regression of #145)

### ISSUE THREAD

**Issue by NickSto** [galaxyproject/usegalaxy-playbook#150]
Creating a new issue since I don't have permissions to re-open #145.

Getting this error again: 
> awk: error while loading shared libraries: libmpfr.so.4: cannot open shared object file: No such file or directory

This time it happened on the **Du Novo: Correct barcodes** tool, though, instead of **Du Novo: Make families**. The latter runs successfully.

@natefoo

**Comment by natefoo** [comment]
There were two conda environments (for different versions of the tool) that still had gawk from bioconda installed. I reinstalled gawk in those envs from conda-forge and they should be fixed now. Those envs were apparently installed on 2018-06-07, before the bioconda gawk was marked "broken" by @bgruening on 2018-06-20. Future dunovo conda environments should not have this issue.

**Comment by NickSto** [comment]
@natefoo Thanks! Just tried it, looks fixed.

Good to know more about what went wrong, too.
