### ISSUE TITLE
Workflows are launching but not producing output datasets

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#151]
Starting test history: https://usegalaxy.org/u/jen/h/test-history-dinky-wf 

Two workflows exacted, include one tool each, same but a different version. Both created new histories but failed to produce output. The tools run normally from the history.

Possibly related: Workflow fails to launch after extracting and using "run" link, with no warnings https://github.com/galaxyproject/galaxy/issues/6522 

----

test 1

 - Extracted wf 1, run on starting test history above (input data1): https://usegalaxy.org/u/jen/w/workflow-constructed-from-history-test-history-dinky-wf-vcf-to-tab-v003 
 - Sent to this history: https://usegalaxy.org/u/jen/h/workflow-constructed-from-history-test-history-dinky-wf-vcf-to-tab-v003

----

test 2

 - Extracted wf 2, also run on starting test history above (input data1): https://usegalaxy.org/u/jen/w/workflow-constructed-from-history-test-history-dinky-wf-vcf-to-tab-v100rc1galaxy0
 - Sent to this history: https://usegalaxy.org/u/jen/h/workflow-constructed-from-history-test-history-dinky-wf-vcf-to-tab-v100rc1galaxy0

----

test 3

 - Extracted wf 2, run on copy of starting test history above (input data1): https://usegalaxy.org/u/jen/w/workflow-constructed-from-history-test-history-dinky-wf-vcf-to-tab-v100rc1galaxy0
 - Not sent to a new history, just the original (input data1). https://usegalaxy.org/u/jen/h/copy-of-test-history-dinky-wf 

No new output from workflow. This is what the GUI looks like. History refresh pop-up seems "sticky" but that is a side issue.

<img width="994" alt="screen shot 2018-07-20 at 3 54 30 pm" src="https://user-images.githubusercontent.com/8999735/43028541-4640af64-8c35-11e8-96d4-ed19b7636721.png">

----

Biostars post about workflow issues today: https://biostar.usegalaxy.org/p/28818

ping @dannon

**Comment by dannon** [comment]
@guerler Think this is related to the same changes that required the `exact_version=False` fix which we deployed last week?

**Comment by drthanwho** [comment]
This is still an ongoing problem for me too however.

**Comment by dannon** [comment]
I didn't mean related to the fix itself, but related to the bug that that fix fixed (in that context).  Whatever necessitated that fix changed the way workflow module injection handled tool versions, which seems to be what's borked here?

And, I believe usegalaxy.eu is slightly behind usegalaxy.org in terms of a deployed version, so this would be a recent-ish stable change, I think?

**Comment by bgruening** [comment]
If I'm not wrong we are running 3fe88a9bfe1b010ca30ffac32e5c4e200398c48e

**Comment by dannon** [comment]
@bgruening Thanks, good to know!  So, maybe this bookends the changes to dig through, between 3fe88a9bfe1b010ca30ffac32e5c4e200398c48e (July 5, usegalaxy.eu) and ef702e1458f746299710e9ce5afb7b350b61f91c (July 17, on usegalaxy.org)?

**Comment by guerler** [comment]
Thanks for narrowing it down. I tried to run test 3 from above and it worked fine locally.

**Comment by jennaj** [comment]
Retested at usegalaxy.org

tests 1/2 (send results to new history) - older launched workflows had the jobs go through today into the prior "send to new history". also works if run fresh and sent to a new history, example: https://usegalaxy.org/u/jen/h/workflow-constructed-from-history-test-history-dinky-wf-vcf-to-tab-v100rc1galaxy0-7-27  

test3 (default, output in same history) - same result, older launched workflow's jobs were run and running it again also creates the data

Looks fixed! I'll update Biostars https://biostar.usegalaxy.org/p/28818

**Comment by NickSto** [comment]
Working for me too now. Even old workflow runs I'd given up on now seem to have finished and their datasets appeared.

**Comment by dannon** [comment]
Yeah, needed some manual intervention on Friday, but everything should be scheduled and in the clear now, over the weekend, including past runs.
