### ISSUE TITLE
Update SnpEff tools to capture important bug fix (download) and new sub-tools 

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#157]
MTS: https://toolshed.g2.bx.psu.edu/view/iuc/snpeff/dd3622f501f3

**Currently at .org:**

SnpEff download v 4.3+T.galaxy1 (has the key bug)
SnpEff databases v 4.3+T.galaxy1
SnpEff eff v 4.3+T.galaxy1

**Update:**

 - [x] SnpEff download v 4.3+T.galaxy2

**Add:**

 - [x] SnpEff build v 4.3+T.galaxy3
 - [x] SnpEff chromosome info v @wrapper_version@.galaxy1

https://github.com/search?q=org%3Agalaxyproject+snpeff&type=Issues
https://github.com/search?q=org%3Agalaxyproject+snpeff&type=Commits

**Comment by jennaj** [comment]
All updated, no bug reports about them.

MTS most current versions are:

<img width="952" alt="screen shot 2018-12-17 at 3 05 35 pm" src="https://user-images.githubusercontent.com/8999735/50121409-8aeb0800-020d-11e9-9f58-0c9ddecd5f9c.png">

**Comment by jennaj** [comment]
Test for the biggest bug fix in here (closed out now): https://github.com/galaxyproject/tools-iuc/issues/1354#issuecomment-448035637

Short description: Tool wasn't retrieving the right database when it was nested. Now it does.

**Comment by wm75** [comment]
@jennaj the newly added chromosome-info subtool seems rather broken.
- With the *Download on demand* option it fails with a  `java.lang.RuntimeException: Cannot create directory '/cvmfs/main.galaxyproject.org/deps/_conda/pkgs/snpeff-4.3.1t-0/share/snpeff-4.3.1t-0/data/...` error indicating that the tool tries to write outside the job working directory
- The *Downloaded snpEff database in your history* option fails to recognize suitable datasets - so you can't use it
- The *locally installed snpEff database* option I couldn't test on main because there doesn't seem to be any suitable database installed, but on the eu server this mode produces an OutOfMemoryy error

That leaves only the *Custom ...* option, which I don't have a  test dataset for.

**Comment by jennaj** [comment]
Yo! Ok, those are problems. Didn't test everything (just that the requested nested snpeff genome was _reportedly_ downloaded). Glad for the additional testing!

Want to open another ticket against the tool repo with this info? If could link it back, would be helpful. 

Maybe the tools need more test cases, too?

I'll probably make a new "update when fixed" ticket for main here and reference this one. I can build some test history/cases up, including for _Custom_ (is for output from using **SnpEff build**) and add to the ticket -- unless you do that first. Will look for a small genome with sufficient annotation available (source: GenBank), might actually have that already somewhere...

**Comment by wm75** [comment]
Opened https://github.com/galaxyproject/tools-iuc/issues/2254. Yes, a PR should definitely also add more thorough tests.

**Comment by wm75** [comment]
All the *chromosome-info* issues above and a related one with downloading a genome source on demand in snpEff *eff* have been addressed by @lparsons in https://github.com/galaxyproject/tools-iuc/pull/2255. The tools have been updated in the MTS and on usegalaxy.eu and are working just fine now.

**Comment by jennaj** [comment]
Hi @wm75 -- I don't see updated tool revisions in the MTS but the repo update-date is newer now (1/25/19). EU server seems to be down so I can't compare against there right now. 

What parts of the tool suite should we update from the MTS? 

cc @davebx Re-opening this. Two things (at least) were changes to address issues. Might not have an updated tool version.

**Comment by jennaj** [comment]
@davebx The tool version didn't change, so just lmk when the suite update is installed and I will test vs prior issues.

**Comment by davebx** [comment]
Updated to toolshed revision 8f92c2b26e6d on usegalaxy.org

**Comment by jennaj** [comment]
Thanks, testing

**Comment by jennaj** [comment]
Testing took longer than I expected, but am now convinced the tools are finally working correctly. Super!

Test history with most items (messy): https://usegalaxy.org:/u/jen/h/agamp3-snpeff-test 

The "HTML stats" from toolshed.g2.bx.psu.edu/repos/iuc/snpeff/snpEff/4.3+T.galaxy1 renders oddly but it might just need to be whitelisted, then we can close this out. ping @natefoo @martenson @davebx

**Comment by natefoo** [comment]
It looks like **SnpEff eff** version 4.3+T.galaxy1 is whitelisted and the latest HTML output in your test history looks ok to me? Closing this but feel free to reopen if it still seems broken.
