### ISSUE TITLE
Get Data > EBI SRA is assigning fastqsanger to fastqsanger.gz output -- tracking ticket

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#158]
Original issue: https://github.com/galaxyproject/galaxy/issues/6334

Retest once on main

**Comment by dannon** [comment]
@jennaj Main has been updated, retest whenever.

**Comment by jennaj** [comment]
**Note to usegalaxy.* users:** This is resolved at usegalaxy.org now. It will be resolved soon at usegalaxy.eu and usegalaxy.org.au and other public Galaxy servers when those servers update to the next Galaxy release.
