### ISSUE TITLE
Should we add "add_input_name_as_column" to Text Mani tool group at .org?

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#159]
Seems really useful: https://toolshed.g2.bx.psu.edu/repository?repository_id=050cbba300e2dbed&changeset_revision=b31219f26a8f

Came up at Gitter today, didn't know it existed before that: https://gitter.im/galaxyproject/Lobby?at=5ba26645be4f300626b942ea

Could go in Text Mani and/or Collection operations -- works with both individual files and collections

If it is already there, it isn't showing up with a tool panel search, or I am doing something else wrong (?)

thoughts? @nekrut @jxtx

**Comment by martenson** [comment]
https://usegalaxy.org/?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fmvdbeek%2Fadd_input_name_as_column%2FaddName%2F0.1.1&version=0.1.1&__identifer=bdqxc4270sq
