### ISSUE TITLE
DESeq2 2.11.40.2 fails when given Kallisto inputs due to a missing dependency (needs bioconda deseq2 package fix)

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#161]
**issue:** An upstream problem with the DESeq2 Bioconda package recipe causes a dependency-related failure when Kallisto inputs are used. GTF vs tabular ref anno for transcript-gene not a factor, using either triggers the error. A ticket against that repo was created here: https://github.com/bioconda/bioconda-recipes/issues/11141

**workaround:** Using Kallisto inputs is not possible at this time if working at https://usegalaxy.org. Choose a different count input type.

**posible to fix now?** @davebx @natefoo Would be able to repair this somehow at https://usegalaxy.org before the upstream fix is made/propaged? So users can get successful jobs now instead of waiting?

**cc** @bgruening @Slugger70 -- this may present at .eu and/or .org.eu already, or you may hit it soon if/when upgrading the tool. The error came up under the 18.09 pre-release at .org but the galaxy version seems to be unrelated (vetted with Nate first and he isolated the root cause to the bioconda package). I didn't run a direct test at your usegalaxy.* servers for this error and don't have an anon-data test history created for it at .org (yet -- will do once when have time or when testing the fix at .org), but both could be done/prioritized sooner if would be helpful. 

**MTS/tool id:** toolshed.g2.bx.psu.edu/repos/iuc/deseq2/deseq2/2.11.40.2

**Error at .org under 18.09:**

> Fatal error: An undefined error occurred, please check your input carefully and contact your administrator.
> Note: importing `abundance.h5` is typically faster than `abundance.tsv`
> reading in files with read.delim (install 'readr' package for speed up)
> 1 Error in infRepImporter(dirname(files[i])) : 
>   reading kallisto results from hdf5 files requires Bioconductor package `rhdf5`
> Calls: get_deseq_dataset -> tximport -> infRepImporter

**Comment by bgruening** [comment]
This fixes it locally:

```
   source activate mulled-v1-dbc1e05d0db06d983572e7eca0df68af225d8f398b6e11dd4d586075518c4101/
   conda install bioconductor-rhdf5
```

A new installation should also fix it - I fixed it upstream as well.

**Comment by nvanduse** [comment]
Awesome! Thanks
-Nate

**Comment by jennaj** [comment]
running a quick test -- will close out if successful. Thanks!
