### ISSUE TITLE
Add tool "Replace chromosome names" or "Replace column by values"

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#162]
Tools are both available at .eu.  

> All entries of a column can be replaced by a given value. This value is determined with the key-value principle. This is useful if someone wants to replace e.g. the chromosomes notation in ensembl notation by the ones from UCSC.

Replace chromosome names in a tabular dataset using a mapping table (Galaxy Version 0.1) https://toolshed.g2.bx.psu.edu/view/earlhaminst/replace_chromosome_names/6c0373cc070f

Replace column by values which are defined in a convert file (Galaxy Version 0.1 at .eu -- 0.2 in MTS) https://toolshed.g2.bx.psu.edu/view/bgruening/replace_column_by_key_value_file/d533e4b75800

**Comment by martenson** [comment]
https://usegalaxy.org/?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fmvdbeek%2Fadd_input_name_as_column%2FaddName%2F0.1.1&version=0.1.1&__identifer=bdqxc4270sq

**Comment by martenson** [comment]
Actually I do not see `replace_chromosome_names` on Main.

**Comment by martenson** [comment]
oh, it was OR, nevermind
