### ISSUE TITLE
Consider adding all bcftools to main

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#167]
MTS: https://toolshed.g2.bx.psu.edu/view/iuc/suite_bcftools_1_3/488e382af384

note: these are not conda based

Related Q&A: https://biostar.usegalaxy.org/p/29664/

**Comment by dannon** [comment]
On main now.  @jennaj is going to test/verify later on, but please do reopen/ping me if something's busted.

**Comment by dannon** [comment]
@jennaj Didn't see  you'd tagged and reassigned (my issue hadn't refreshed when I commented/closed), sorry, reopening for you to track it!

**Comment by gregvonkuster** [comment]
@jennaj In case you are interested in including 2 additional "bcftools" tools, here are 2 that I've built for one of my customers:

https://toolshed.g2.bx.psu.edu/view/greg/affy2vcf/6274184a8b84 - converts raw Affymetrix sequencing data to BCF/VCF

https://testtoolshed.g2.bx.psu.edu/view/greg/bcftools_sort/5486fb1fb923 - sorts BCF/VCF files.  The sort feature was introduced after the bcftools version that is in the tools-iuc repo, so it is not included in that suite.  This tool is not yet contained in the MTS, but I'll add it there now.

**Comment by jennaj** [comment]
@gregvonkuster Let's put this in a new ticket and track it there. Decide/work on it after the holiday, just in case something goes wrong with the install/config on main. 

I'll make that ticket and link it back. We should follow up on MTS status, etc there.

Thanks!!

**Comment by jennaj** [comment]
Tools from MTS are not present and the tool menu looks good. Closing & Thanks!
