### ISSUE TITLE
Workflows sent to a new history do not always populate the output datasets

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#168]
Sometimes the data populates and sometimes it doesn't.

Start by importing this history for the initial datasets. You only really need data 2 (a fastq dataset): https://usegalaxy.org:/u/jen/h/test-workflow-simple-input 

Then import this workflow, has one step (FastQC): https://usegalaxy.org/u/jen/w/workflow-constructed-from-history-test-workflow-simple-input

Execute the workflow and send the results to a new history. Do this a few times. Note that some of the newly created histories have no datasets in them.

**UPDATE**: The histories that used to have no datasets originally (after waiting an hour) now do four hours later (??) but you can still see that one of the new launched test that still does not have datasets. 

Secondary issue: I renamed v6 and v7 from the My Histories list pull-down. Something odd happened with the names.

<img width="1017" alt="screen shot 2018-10-12 at 12 26 52 pm" src="https://user-images.githubusercontent.com/8999735/46890195-db637500-ce1a-11e8-9aca-0021f23d4af7.png">

**Comment by jennaj** [comment]
Hum, now all of these have datasets in them. Is something is causing a delay?

**Comment by dannon** [comment]
Regarding the delay, that's definitely possible depending on the process that's handling scheduling of workflow invocations.

The naming is a bug, I'll take a look at that now.

**Comment by jennaj** [comment]
The history renaming bug is ticketed here now: https://github.com/galaxyproject/usegalaxy-playbook/issues/169

Thanks!

**Comment by dannon** [comment]
As mentioned, I think what was reported here is due to the restarts on main on Friday.  Workflow handlers were delayed in scheduling, and that explains what you've seen in terms of them not immediately showing outputs but them showing up later (when they were processed after restart).

**Comment by jennaj** [comment]
This is faster now and I can't reproduce, so I think the restarts were the issue too, makes sense. Thanks!
