### ISSUE TITLE
Renaming histories that contain ' quotes are problematic

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#169]
> ` 

does not cause a problem

> ' 

does cause a problem

Everything before the END was the original history name, everthing after is what I added during renaming.

<img width="285" alt="screen shot 2018-10-12 at 12 42 43 pm" src="https://user-images.githubusercontent.com/8999735/46890756-a0fad780-ce1c-11e8-9723-efa9ab3df076.png">

**Comment by jennaj** [comment]
I'd like to leave this open until the fix is made and applied to Main. I'm still seeing the problem and the ticket in /galaxy is still open.

<img width="275" alt="screen shot 2018-10-24 at 4 38 00 pm" src="https://user-images.githubusercontent.com/8999735/47467497-70675600-d7ab-11e8-8477-38b0827a3e5c.png">

**Comment by jennaj** [comment]
Not fixed at ORG yet

**Comment by martenson** [comment]
should be deployed now

**Comment by jennaj** [comment]
Not available yet on Main, see https://github.com/galaxyproject/galaxy/issues/6873#issuecomment-439106312

**Comment by jennaj** [comment]
Ok, probably not super critical to do and next release is a month or so away. Let's leave this open -- anything with a "retest-fail" here I check upon release updates to main, so will catch it when 19.01 goes live

**Comment by jennaj** [comment]
PR closed and this is added to bug fix project for 1901 integration testing. Going to close this one too. Can reopen if problematic. https://github.com/galaxyproject/galaxy/issues/6873

**Comment by jennaj** [comment]
Passed in 19.01
