### ISSUE TITLE
Tophat2 is bringing up the oldest tool version instead of the newest when loaded from tool panel

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#170]
Is resulting in bug reports as the oldest version (0.6) errors out. 

The version of the wrapper doesn't report that a "newer tool version is available" at the top. However, the Versions menu is fine and does include the latest (2.1.1).

Is this something you could fix @davebx?

**Note for end users:** All versions of Tophat have been deprecated. HISAT2 is the replacement tool. If you have problems running Tophat, try using HISAT2 instead. For usage help, please see this Galaxy tutorial: https://galaxyproject.org/tutorials/nt_rnaseq/, with all tutorials available at https://galaxyproject.org/learn/.

**Comment by martenson** [comment]
the issue might be that tophat is in two sections

**Comment by jennaj** [comment]
Ah, you are right. I was confused about why this wasn't marked as deprecated anymore and was going to ask in lab.

So, the solution is to remove it from the primary RNA-seq tool group, and just leave it in the deprecated tool group (loads correctly). Can you help with that @martenson?

**Comment by martenson** [comment]
The solution is to fix the shed_tool_conf so all tophat tools are in the correct section.

**Comment by martenson** [comment]
fixed, for those interested this is 'how to': https://github.com/galaxyproject/usegalaxy-playbook/wiki/Main-Toolpanel-Maintenance
