### ISSUE TITLE
Update Uniprot to version 0.2 (version 0.1 has a bug or simply doesn't work with the Uniprot API anymore)

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#172]
**Workaround for users:** Use the tool at Galaxy EU https://usegalaxy.eu. Search the tool panel with "Uniprot". Two versions of the tool are listed. **Be sure to use version 0.2 or expect an error**. 

**MTS repo:** https://toolshed.g2.bx.psu.edu/view/bgruening/uniprot_rest_interface/054483e27a35

**Error at ORG v1:** HTML is probably being returned due to some conflict with the updated Uniprot API (same as at EU), but ORG is not parsing it the same way, instead it is tossing a python/unicode error.

```
Fatal error: Exit code 1 ()
Traceback (most recent call last):
  File "/galaxy/main/shed_tools/toolshed.g2.bx.psu.edu/repos/bgruening/uniprot_rest_interface/48522382b6a4/uniprot_rest_interface/uniprot.py", line 74, in <module>
    args.out.write(_map(query, args.f, args.t, args.format))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 2246: ordinal not in range(128)
```

**Error at EU v1:** Mangled HTML output instead of result list, see test history below.

**Test histories:**

 - ORG, v1 https://usegalaxy.org:/u/jen/h/test-history-uniprot
 - EU, v1 & v2 https://usegalaxy.eu/u/jenj/h/test-history-uniprot

**Prior issues with this tool:** _Uniprot tool has a dependency problem at http://usegalaxy.org_ https://github.com/galaxyproject/galaxy/issues/3721

**A related tool that has an install request already at ORG (has some functionality overlap).** If you want to use this too now, use it at Galaxy EU: _Add tool annotateMyIDs to main_ https://github.com/galaxyproject/usegalaxy-playbook/issues/141

**Uniprot FAQs:** "Entry name" translates to "UniprotKB ID" on the Galaxy tool form ("ID" is the older way Uniprot used to classify the identifier "Entry name"). 
 - https://www.uniprot.org/help/entry_name
 - https://www.uniprot.org/help/difference_accession_entryname
 - https://www.uniprot.org/help/uploadlists (tests use the example entry name from here)

**Comment by jennaj** [comment]
@davebx Please let me know if you need more info to do the tool update. Once done, please ping me here and at slack so I'm sure to see it and get the revision tested & closed out soon.

**Comment by davebx** [comment]
Updated in https://github.com/galaxyproject/usegalaxy-playbook/commit/9a476008536d522bc34e82816ae82292682797d5

**Comment by jennaj** [comment]
Thank you, v 0.2 works! Test in here, data 3 https://usegalaxy.org:/u/jen/h/test-history-uniprot

Closing
