### ISSUE TITLE
run own botbot server?

### ISSUE THREAD

**Issue by martenson** [galaxyproject/usegalaxy-playbook#173]
btobot as a service is shutting down: https://lincolnloop.com/blog/saying-goodbye-botbotme/

should we run our own? https://botbot.readthedocs.io/en/latest/index.html

ping @tnabtaf @natefoo

**Comment by tnabtaf** [comment]
Well, dang.  BotBot.me shuts down Nov 5, or in about a week.  We have no way of knowing how often it gets used.  It is included in the pan-Galactic google search, but it appears to only search recent posts, so BotBot is only providing half of what I want it to, which is 

1. a complete searchable archive.
2. A nice GUI

So, I say we *don't* set up our own BotBot server.  I would like to have something we can search though.

**Comment by natefoo** [comment]
Considering Lincoln Loop is shutting it down over GDPR concerns, wouldn't we have the same concerns? I think sadly we may need to discontinue offering public logs for the same reasons.

**Comment by martenson** [comment]
@natefoo that is a legit point, maybe we shouldn't offer public logs after all
