### ISSUE TITLE
Retest qname_sorted.bam datatype once main next restarted

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#174]
Test history: https://usegalaxy.org:/u/jen/h/test-history-qnamesortedbam

Tests:

 - [ ] No index listed under disc icon (directly initiates BAM download only)
 - [ ] Upload assigns the datatype `qname_sorted.bam` using autodetect

PR fix: https://github.com/galaxyproject/galaxy/commit/ddeef3fbc2f884d8ad1af95adc164ca8e5bc15c3

Related tickets:
https://github.com/galaxyproject/galaxy/issues/6945
https://github.com/galaxyproject/galaxy/issues/6949

**Comment by martenson** [comment]
this should be ready for test on Main now

**Comment by jennaj** [comment]
The datatype is still autodetected as `unsorted.bam`, for both my original qname test bam and the official qname test bam added to the /galaxy repo today.

Correctly, the indexes are no longer listed under the disc/download function other bams (in other histories) with a `qname_sorted.bam` datatype assigned .. but I like to double check that for a bam not manipulated in any other way except for an Upload using autodetect resulting in `qname_sorted.bam` directly assigned. Then will check that off as a pass, too.

**Comment by martenson** [comment]
@mvdbeek is it this commit? https://github.com/galaxyproject/galaxy/pull/6950/commits/ddeef3fbc2f884d8ad1af95adc164ca8e5bc15c3  I can cherry pick it

**Comment by martenson** [comment]
backported now

**Comment by jennaj** [comment]
Just reran the test with the same result. Am guessing I need to wait for a restart on main, then test.

**Comment by martenson** [comment]
@jennaj correct, we need to deploy it first

**Comment by jennaj** [comment]
Rested and all works as we want now. Huge thanks!! Closing this one out
