### ISSUE TITLE
Unicycler 0.4.1.1 (older) and 0.4.6.0 (latest) PLUS Trinity 0.0.1 seem to have config problems.

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#176]
Looks like the Bridges cluster started to have some nodes fail starting a few days ago and now is completely failing for all runs, both tools.

**Tools:**

 - toolshed.g2.bx.psu.edu/repos/iuc/unicycler/unicycler/0.4.1.1 (previous version)
 - toolshed.g2.bx.psu.edu/repos/iuc/unicycler/unicycler/0.4.6.0 (latest)
 - toolshed.g2.bx.psu.edu/repos/nate/trinity_psc/trinity_psc/0.0.1

**Test histories:** 

 - https://usegalaxy.org:/u/jen/h/test-history-unicycler-train-data 
 - https://usegalaxy.org:/u/jen/h/test-history-trinity

**Unicycler errors (mostly) like this**: Other errors submitted from runs in prior few days are likely content/param issues, see galaxy-bugs. But even if that part is resolved, the user would hit this problem.

```
stderr
code 17: slurm_submit_batch_job error: Invalid account or account/partition combination specified

stdout

Job Information
Remote job server indicated a problem running or monitoring this job.
```

**Unicycler error variation:** (probably content related -- eg job too large, double checking, but including here in case is helpful)

```
stderr
code 17: slurm_submit_batch_job error: Job violates accounting/QOS policy (job submit limit, user's size and/or time limits)
```

**Trinity error:**

```
stderr
code 17: slurm_submit_batch_job error: Invalid account or account/partition combination specified

Job Information
Remote job server indicated a problem running or monitoring this job.
```

**Trinity error variation:** Came in a few days before the current error, see galaxy-bugs for details.

```
stderr
slurmstepd: error: *** JOB NNNN ON l023 CANCELLED AT 2018-09-17T14:57:26 DUE TO NODE FAILURE, SEE SLURMCTLD LOG FOR DETAILS ***

stdout
workdir is /pylon5/mc48nsp/xcgalaxy/main/staging/NNNN/working
Running Trinity from /local/NNNN

Job Information
Remote job server indicated a problem running or monitoring this job.
```

**Comment by jennaj** [comment]
Resolution is a priority and expected to be completed soon. Our team will post back here when the tools are ready to use again.

**Comment by somi06** [comment]
Any progress on fixing this?

**Comment by jennaj** [comment]
@somi06 The server correction was made last week. The tests I ran today passed, so this issue is now fully resolved and you can run your Trinit/Unicycler jobs now if you haven't already started them up.

**Comment by somi06** [comment]
I still cannot get it to work on galaxy.

**Comment by jennaj** [comment]
@somi06 This is an older, resolved ticket.

There is a new problem with the Unicycler tool that we are working on (Trinity is not impacted).

Please see: https://github.com/galaxyproject/usegalaxy-playbook/issues/185

Thanks for asking, these two tickets should be linked to avoid confusion -- this post should do that.
