### ISSUE TITLE
The steps for moving to discourse

### ISSUE THREAD

**Issue by martenson** [galaxyproject/usegalaxy-playbook#179]
- [x] change all settings on discourse to our initial liking (@martenson @jennaj @tnabtaf)
    - [x] @martenson
    - [x] @jennaj
    - [x] @tnabtaf
- [x] change links in Galaxy / on Main (@martenson)
- [x] add slide to Main (@tnabtaf, @martenson)
- [ ] add slide to galaxy-hub (@tnabtaf, @martenson)
- [x] change links + content in galaxy-hub referencing Biostars (@tnabtaf @jennaj)
- [x] integrate into pan-galactic Google search (@tnabtaf)
- [x] prepare tweet
~~- [ ] prepare hub-blog with usage basics (@jennaj)~~
- [x] Create news item
- [ ] Describe in December news. (@tnabtaf)
- [x] create pinned "Welcome" post at discourse
 ~~- [ ] create the final post at Biostars site pointing to Discourse and related links (hub-blog). We want this to be bumped to the very top before we archive the site (@jennaj)~~ Replaced by landing page/warning header, see "admin-y" below
 - [x] purge all of the testing posts (@marten @jennaj @tnabtaf)
 - [x] review&update privacy policy https://help.galaxyproject.org/t/privacy-policy/6/2 
    - [x] @martenson
    - [x] @jennaj - @martenson removed 3rd party data sharing (marketing/advert)
    - [x] @tnabtaf
 - [x] review&update FAQ https://help.galaxyproject.org/t/faq-guidelines/5/2 
    - [x] @martenson
    - [x] @jennaj - @tnabtaf added the galaxy code of conduct to top
    - [x] @tnabtaf
 - [x] review&update ToS https://help.galaxyproject.org/t/terms-of-service/4/2 
    - [x] @martenson
    - [x] @jennaj -- reviewed default, but did not make changes. Changes are needed. Update: DONE, @martenson replaced with Galaxy terms & conditions & stripped out default CC licence
    - [x] @tnabtaf
- ~~[ ] Add Google Analytics (@martenson)~~

admin-y tasks
- [x] host static copy of biostar (@martenson @natefoo)
- [x] add warning header to the static-only pages backup for biostar (@martenson)
- [x] new landing page for Biostars with: pointers to Discourse, how to search the read-only archive
- [x] change url to help.galaxyproject.org
- [x] set up admins and moderators, revoke testing permissions
- [x] Update title logo to Galaxy Help
- [x] have disabled https://galaxy.trydiscourse.com/
- [x] remove biostar from Main config
- [x] remove biostar from Test config

**Comment by martenson** [comment]
Something to consider: https://meta.discourse.org/t/discourse-github/99895

**Comment by tnabtaf** [comment]
Created a [`biostar-to-discourse`](https://github.com/galaxyproject/galaxy-hub/tree/biostar-to-discoursebranch) in the Hub.

There's a lot to do:
```
git grep -il biostar
admin/gies/index.md
archive/dev-news-briefs/2012-10-23/index.md
archive/dev-news-briefs/2014-06-02/index.md
archive/dev-news-briefs/2014-08-11/index.md
archive/dev-news-briefs/2014-10-06/index.md
archive/dev-news-briefs/2015-01-13/index.md
archive/dev-news-briefs/2015-03/index.md
cloud/jetstream/troubleshooting/index.md
cloudman/troubleshooting/index.md
events/2017-05-arabic/index.md
events/2019-03-compbio-starter/index.md
events/archive/index.md
events/gcc2014/abstracts/talks/index.md
events/gcc2014/bofs/galaxy-admins/index.md
events/gcc2014/bofs/using-galaxy-ui-overview/index.md
events/gcc2015/bofs/galaxy-scientists/index.md
events/gmod-summer-school2014/index.md
events/stanford-workshop/2015-04-01/index.md
ftp-upload/index.md
galaxy-project/statistics/index.md
galaxy-qa/index.md
galaxy-updates/2014-05/index.md
galaxy-updates/2014-06/index.md
galaxy-updates/2014-07/index.md
galaxy-updates/2014-10/index.md
galaxy-updates/2014-11/index.md
galaxy-updates/2014-12/index.md
galaxy-updates/2015-02/index.md
galaxy-updates/2015-04/index.md
galaxy-updates/2015-12/index.md
galaxy-updates/2017-06/index.md
issues/index.md
mailing-lists/index.md
news/2014-05-galaxy-update/index.md
news/2014-06-galaxy-update/index.md
news/galaxy-biostar-launch/index.md
news/gcc2015-data-wrangling-hackathon/index.md
news/irc-public-log-proposal/index.md
search/index.md
support/about-galaxy/index.md
support/biostar/index.md
support/chrom-identifiers/index.md
support/index.md
support/tool-error/index.md
support/tool-help/index.md
support/tool-issues/index.md
teach/resource/galaxy-project-workshop2015/index.md
tools/index.md
tutorials/chip/index.md
tutorials/collections/a
tutorials/collections/index.md
tutorials/g101/index.md
tutorials/ngs/index.md
tutorials/pt_gfam/index.md
```

I'll start with pages in `events`, `galaxy-updates` and `news`.

**Comment by tnabtaf** [comment]
Taking on `dev-news-briefs` and `tutorials` pages now.

**Comment by martenson** [comment]
These are the requirements for the trust level 3: 
![screenshot 2018-11-27 10 49 29](https://user-images.githubusercontent.com/1814954/49093477-2ce08b80-f232-11e8-98e2-a9e9d8b732d8.png)

**Comment by martenson** [comment]
Tweet text:

>To bring the Galaxy community to a new level we are announcing our new Help site. Point your browsers to help.galaxyproject.org and join the discourse. The old site is archived at https://biostar.usegalaxy.org.

**Comment by martenson** [comment]
https://blog.discourse.org/2018/06/understanding-discourse-trust-levels/

**Comment by jennaj** [comment]
Completed changes to hub support/issue pages above: https://github.com/galaxyproject/usegalaxy-playbook/issues/179#issuecomment-441800946

**Comment by martenson** [comment]
should we just point the tos to https://usegalaxy.org/static/terms.html ?

**Comment by tnabtaf** [comment]
@martenson I like the help-specific version we have now.

**Comment by martenson** [comment]
Tweet is out. https://twitter.com/galaxyproject/status/1068221309379702784

**Comment by martenson** [comment]
archive is up https://biostar.usegalaxy.org

**Comment by martenson** [comment]
All done, closing. Long live the Galaxy Help.

**Comment by erasche** [comment]
- [x] Update training materials (will have been done in https://github.com/galaxyproject/training-material/pull/1170, https://github.com/galaxyproject/training-material/pull/1170/commits/755fb84010d07ea14a30b28f9275463b0a60e202)
