### ISSUE TITLE
Update BEDtools to version 2.27.1 (new in MTS)

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#186]
Version 2.27.1 (and 2.27.2 for "Map Bed") of the tools incorporate many important bug fixes and tool form improvements. 

Example of a problem resolved with new tool form options: Intersect BED will always fail with two BAM inputs in the currently installed version 2.27.0.2. An option to output `bed` output was added in the update and avoids errors that end with a "bug report" message similar to `***** ERROR: writeAllOverlap option is not valid with BAM query input unless bed output is specified with -bed option. *****`

**Workaround for end-users:** Use coordinate sorted `bed` inputs instead (tool: BAM to BED). Or, use `bam` inputs with the tool(s) at https://usegalaxy.eu if you are experiencing errors at https://usegalaxy.org until this issue is closed out and the updated tools are added to https://usegalaxy.org. **At the EU server, double check the top of the tool form to make sure that version 2.27.1 or later is being used** and switch to the latest version as needed using the "Versions" menu at the top of the tool form -- an earlier version of the tool may load by default when loading a form from the left panel. If your job errors for a resource related reason (memory or walltime/runtime), the inputs could really be too large or you might need to sort your inputs (e.g. coordinate sort: chrom + start coordinate).

**MTS**: https://toolshed.g2.bx.psu.edu/view/iuc/bedtools/87ee588b3d45

* Test history ORG: https://usegalaxy.org:/u/jen/h/test2-bedtools-intersectbed 
* Test history EU: https://usegalaxy.eu:/u/jenj/h/test-bam-intersect **works with 2 bam inputs**

ORG bam dataset 26 == EU bam dataset 1
ORG bam dataset 28 == EU bam dataset 2

Tickets/PRs related to the update are numerous, toogle closed/open to review those incorporated in the latest release and pending to-do items: https://github.com/search?q=org%3Agalaxyproject+bedtools&type=Issues

**Comment by jennaj** [comment]
Status -- Rerunning EU test

**Comment by jennaj** [comment]
EU test completed -- updated tool version accepts 2 bam inputs. Updating tool on main should resolve the issue there.

**Comment by jennaj** [comment]
@qiagu I cannot assign this ticket to you. Please check with @natefoo or @martenson to determine why & resolve. Then you can assign yourself :)

**Comment by qiagu** [comment]
@jennaj  well, we've already discussed on slack. I probably can't solve this issue without admin privilege to usegalaxy.org, which I don't think I have right now.

**Comment by jennaj** [comment]
@qiagu Pretty sure that is unrelated. Let's bring the chat back internally again and figure it out :)

**Comment by davebx** [comment]
I was able to give @qiagu admin access last week, so that's no longer a blocker.

**Comment by jennaj** [comment]
Status? @qiagu @davebx

**Comment by qiagu** [comment]
@davebx  Actually, the blocker is still there.

**Comment by davebx** [comment]
I've updated bedtools myself, pending ssh access for @qiagu.

**Comment by jennaj** [comment]
Missing dependencies -- @natefoo fixing

**Comment by natefoo** [comment]
The deps should be fixed now.

**Comment by jennaj** [comment]
Tests are still running but would have failed by now if there was the same issue.

I did have some tests some quickly fail for exceeding memory but that was probably a parameter issue (super large job created by a bad combo, I was testing many options out with intersect-bed). 

I think this tool already has the max memory allocated, so nothing to change. Closing!
