### ISSUE TITLE
All GATK tools should be marked as deprecated at org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#198]
Looks like this got "undone" when the tool panel was updated to synch with the other usegalaxy.* servers.

<img width="284" alt="screen shot 2019-03-04 at 8 50 58 am" src="https://user-images.githubusercontent.com/8999735/53748723-cb484280-3e5a-11e9-81f5-9e1ca5248e16.png">

**Comment by erasche** [comment]
Looks like .eu doesn't include the same deprecations. I'll update us.

@jennaj broader question and probably not the place for it, but, at the risk of asking you to do extra work, would you want to expand the 'functionality on Main' to 'functionality on *', at least for a subset of issues like this one where we want to be consistent?

**Comment by martenson** [comment]
We could keep and share a list of deprecated tools. Yaml anybody?

**Comment by erasche** [comment]
@martenson yeah, something in https://github.com/galaxyproject/usegalaxy-tools would be good. We can figure out the automation later.

**Comment by jennaj** [comment]
@erasche I'll add in a new tag :)

**Comment by jennaj** [comment]
Looks like this is still a problem. Or maybe got reverted in the last revision?

My goal is to learn what is new/valid and what is outdated and to make sure our users can understand that, too, in a clear way, before they waste time running tools that have known issues we won't ever address. How to do that -- I'm flexible!! Whatever works for everyone since we are synching up. 

Maybe move the entire "GATK tools" group down into the "Deprecated" section, plus add the tag for individual tools? People still are using these, getting errors, and not understanding why. The GATK version behind most of these is `1.4`, which is super old by now. The tools fail for all kinds of reasons: some are known wrapper bugs and some are usage issues. But since we aren't fixing the old wrappers, digging into what is going wrong is problematic. And even if the tool doesn't fail, can the result be "trusted"?

This is what ORG's tool panel looks like. All are v 1.4 from what I can tell.

<img width="255" alt="Screen Shot 2019-11-13 at 4 31 56 PM" src="https://user-images.githubusercontent.com/8999735/68816648-edbe6c80-0633-11ea-8e85-e4f72d190568.png">

This is what EU's tool panel looks like. Mix of GATK4 (new, assume is "good"), then the others are a mix of the older v 2.x and v 1.4.

<img width="263" alt="Screen Shot 2019-11-13 at 4 40 01 PM" src="https://user-images.githubusercontent.com/8999735/68816830-894fdd00-0634-11ea-87a5-88b4d2595856.png">

**Comment by jennaj** [comment]
Related ticket, was a suggestion to "hide" any that are deprecated by default. Not sure how others feel about that. 

https://github.com/galaxyproject/usegalaxy-playbook/issues/241

**Comment by jennaj** [comment]
End-users, please see: https://github.com/galaxyproject/usegalaxy-playbook/issues/281#issuecomment-618586374

**Comment by jennaj** [comment]
Reverted again. The only GATK not to mark as deprecated should be `GATK4 Mutect2`.

Users get confused when tool panel search and do not view the tool section -- each tool should be annotated.

Ideas about how to keep this from getting unset?

**Comment by jennaj** [comment]
All GATK 1.4 tools have been removed from the server as deprecated and non-functional.

Closing
