### ISSUE TITLE
move the disposable_blacklist out of secret vars

### ISSUE THREAD

**Issue by martenson** [galaxyproject/usegalaxy-playbook#20]
the project is public anyways: https://github.com/martenson/disposable-email-domains
and it will be easier to keep up to date (we might also want to automate it?)

ping @natefoo

**Comment by natefoo** [comment]
I guess. Sorta defeats the purpose.

**Comment by martenson** [comment]
@natefoo the purpose is to make it difficult to use disposable address which is why we blacklist the services that make it easy and this is best done when the blacklist is public.

Everybody can create <random_thing>@gmail.com and we will never have a chance to block them anyways.

**Comment by natefoo** [comment]
K.
