### ISSUE TITLE
Whitelist these tools for HTML display

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#203]
- [x] **Krona pie chart** from taxonomic profile (Galaxy Version 2.6.1.1)

 - Related ticket with test history: https://github.com/galaxyproject/usegalaxy-playbook/issues/74. 
 - Ticket from 2.6.1 update testing: https://github.com/galaxyproject/usegalaxy-playbook/issues/73
 - **Workaround for end users** -- try version 2.6.1 instead until this ticket closes out

- [x] **SnpEff eff**: annotate variants (Galaxy Version 4.3+T.galaxy1)

 - Related ticket with test history: https://github.com/galaxyproject/usegalaxy-playbook/issues/157#issuecomment-470289669
 - **No workaround available**

ping @davebx or @natefoo ??

**Comment by natefoo** [comment]
- **Krona pie chart** is done
- **SnpEff eff** was already done (not sure when)

**Comment by jennaj** [comment]
I whitelisted through the GUI while testing. Maybe just took some time to propagate. 
Krona look good now, too. Thanks!
