### ISSUE TITLE
Missing dep - wigToBigWig or bedGraphToBigWig: error while loading shared libraries: libssl.so.1.0.0

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#208]
Full error: 

`wigToBigWig: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory`

Tools: 

 - Edit Attributes>Convert: Convert BedGraph to BigWig (Galaxy Version 1.0.1)
 - Tool Panel: Wig/BedGraph-to-bigWig converter (Galaxy Version 1.1.1)

Test history:

https://usegalaxy.org:/u/jen/h/test-bedgraph-converts

ping @natefoo

**Comment by jennaj** [comment]
Other tools can hit this problem when the convert is an intermediate step or a different convert function is called (resulting in bigwig). 

Some Bedtools operations and Edit Att BAM > Bigwig are examples.

**Comment by natefoo** [comment]
This is due to an issue with the bioconda packages that @bgruening fixed with a rebuild a few days ago. I have updated to the fixed builds of these packages, which should fix this error.

**Comment by jennaj** [comment]
Reran -- one tool worked, other two are queued. Looks good unless those later fail, same test history as before. Closing out. Thanks for quick fix Nate!
