### ISSUE TITLE
unable to schedule some jobs of a workflow

### ISSUE THREAD

**Issue by martenson** [galaxyproject/usegalaxy-playbook#211]
This works when run on usegalaxy.eu, or when you run the step manually. From @bwlang:

>I’m trying to build a public facing DNA library QC workflow on usegalaxy.org… It nearly matches the workflow we use on our internal galaxy which seems to work fine, but oddly - the last step (multiqc) does not seem to create a history item when I run it. Neither does the terminal krona step. I don’t see any errors. The the preceeding jobs seems to have been successful. I can’t find these as hidden or deleted datasets. Am I missing something basic here?
workflow: https://usegalaxy.org/u/bradlanghorst/w/neb-dna-library-qc
example hisotry: https://usegalaxy.org:/u/bradlanghorst/h/test-qc

Ping @natefoo 

@mvdbeek noted that this might be due to Galaxy trying to schedule multiqc before the dataset discovery of the picard step is finished.

**Comment by natefoo** [comment]
Here's the cause: https://gist.github.com/natefoo/377452234459a9bb59bb9b3e303cea1d

I have temporarily enabled `legacy_eager_objectstore_initialization` as a workaround, watch #7368 for a proper fix.

**Comment by mvdbeek** [comment]
> @mvdbeek noted that this might be due to Galaxy trying to schedule multiqc before the dataset discovery of the picard step is finished.

The legacy eager object store issue and the early scheduling issue should have been fixed, I'll remove https://github.com/galaxyproject/usegalaxy-playbook/blob/8ba6a864533dd707fe17aa09cc1fcece9ec07e08/env/main/group_vars/all/galaxy_config_vars.yml#L184. This is quite likely one of the performance bottlenecks with the covid workflows.

**Comment by martenson** [comment]
I just reran the original example, and all went fine. Thanks for fixing.
