### ISSUE TITLE
HISAT2 fails when run at Stampede

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#214]
@natefoo Looking at this. 

Fails with an error like 

```
Remote job server indicated a problem running or monitoring this job.
```

Test history .. doesn't contain this failure but can be used for re-run (test jobs are data 12-13-14 and grayed out in this test history, maybe by nate): https://usegalaxy.org:/u/jen/h/test-byte-range-issue-w-mappers-hisat2-star-bowtie

**Comment by jennaj** [comment]
The smaller test job ended. Slightly different error than before. Dataset 12 (red) -- other outputs same job (13/14) stayed gray, so has a disconnect in job state refresh.

Other clusters can find the index, so that is also server-specific and likely expected right now.

```
Dataset Error
An error occured while running the tool toolshed.g2.bx.psu.edu/repos/iuc/hisat2/hisat2/2.1.0+galaxy4.

Tool execution generated the following messages:

Fatal error: Matched on hisat2-align exited with value 1
Could not locate a HISAT2 index corresponding to basename "/cvmfs/data.galaxyproject.org/managed/hisat2_index/mm9/mm9"
Error: Encountered internal HISAT2 exception (#1)
Command: /work/galaxy/main/deps/_conda/envs/mulled-v1-e7321ba46fa5ea4c6b9a06b78e6cd5182b33c0a47c2c86b5d610e1361f8b1686/bin/hisat2-align-s --wrapper basic-0 -p 272 -x /cvmfs/data.galaxyproject.org/managed/hisat2_index/mm9/mm9 -1 input_f.fastq -2 input_r.fastq 
(ERR): hisat2-align exited with value 1
```

`occured` is still misspelled. Think fixed in 19.05, will confirm.

**Comment by jmchilton** [comment]
/cvmfs isn't available - so we need to make sure HISAT jobs are not sent to Stampede.

**Comment by natefoo** [comment]
They will only go to Stampede if it is explicitly selected.

The dynamic rule needs to be updated - I search for the cached/history option in a number of tools and "punt" them off Stampede if cached is selected. HISAT2 needs to be added (and `GENOME_SOURCE_PARAMS` and `GENOME_SOURCE_VALUES` updated if necessary) in [the dynamic rule](https://github.com/galaxyproject/usegalaxy-playbook/blob/master/env/common/files/galaxy/dynamic_rules/multi_dynamic_walltime.py#L250).
