### ISSUE TITLE
Fix VCFFilter

### ISSUE THREAD

**Issue by VJalili** [galaxyproject/usegalaxy-playbook#216]
>Status 1/21/19: the Updated tool is in MTS, ready to install
Status 2/12/19: Not installed yet, pinged in ticket
Status 2/15/19: Installed and tested. Tool form "help" rendering problems & new issue with "invert" and mixed operator problem found (old+new version). See https://github.com/galaxyproject/tools-iuc/issues/2300 && https://github.com/galaxyproject/usegalaxy-playbook/issues/182#issuecomment-464163384
>MTS v 1.0.0_rc1+galaxy2: https://toolshed.g2.bx.psu.edu/view/devteam/vcffilter/de885f4afb7f
>Original issues:
>IUC issue: https://github.com/galaxyproject/tools-iuc/issues/1910)
>PR: https://github.com/galaxyproject/tools-iuc/pull/2209
>Test-on-Main ticket: https://github.com/galaxyproject/usegalaxy-playbook/issues/182
>Vahid @VJalili (dev) & @davebx (tool install)

**Comment by VJalili** [comment]
@jennaj 
This should fix the help form rendering issues: https://github.com/galaxyproject/tools-iuc/pull/2383

**Comment by jennaj** [comment]
Great, will close out and link to our main tracking/update-the-tool ticket here https://github.com/galaxyproject/usegalaxy-playbook/issues/182
