### ISSUE TITLE
Add Kraken2 tools and new DM to Test server

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#229]
MTS:

 - Tools: Getting more info about which to install, the MTS is a bit confusing https://gitter.im/galaxy-iuc/iuc?at=5cf042d8faac64393412e3b6
 - DM (new today!): https://toolshed.g2.bx.psu.edu/view/iuc/data_manager_build_kraken2_database/e4cdf82de430

**Please just install on Test first.** 

We should make sure all is working before putting the tools are Main. These don't function without indexes and there were some issues before with mixing Kraken and Kraken2 sub-tools/functions, this is one of them https://github.com/galaxyproject/tools-iuc/issues/2373. I asked about that, too, in the Gitter chat link above.

Am making a distinct ticket for actually creating and testing out the indexes. https://github.com/galaxyproject/usegalaxy-playbook/issues/230

**Comment by dfornika** [comment]
Kraken2 Data Manager: https://toolshed.g2.bx.psu.edu/repository?repository_id=0aecc2cd21d85390&changeset_revision=e4cdf82de430
Kraken2 Tool: https://toolshed.g2.bx.psu.edu/repository?repository_id=9fb960deaaf10080&changeset_revision=328c607150ff

**Comment by jennaj** [comment]
@dfornika What about the other Kraken tools? Are those needed or do they work with Kraken2 also? Or pending updates to Kraken2? Are a few of these.

Thanks!
