### ISSUE TITLE
incompatibility with ansible 2.2

### ISSUE THREAD

**Issue by martenson** [galaxyproject/usegalaxy-playbook#23]
playbook galaxy_configs says:
`
fatal: [galaxy-web-01.tacc.utexas.edu]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'ansible.vars.unsafe_proxy.AnsibleUnsafeText object' has no attribute 'dest'\n\nThe error appears to have been in '/home/marten/usegalaxy-playbook/roles/galaxyprojectdotorg.galaxy/tasks/static_setup.yml': line 7, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Install additional Galaxy config files (static)\n  ^ here\n"}
`

> downgrade to ansible 2.1
i'll fix that... at some point

**Comment by natefoo** [comment]
Fixed!

**Comment by martenson** [comment]
Splendid, thanks a bunch @natefoo !
