### ISSUE TITLE
Summary with ongoing status for quota recalculation issues at usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#259]
This issue will close once the correction is applied to Galaxy Main https://usegalaxy.org.

Details for end-users at this server: 

----

The quota recalculation function was problematic for some use cases in the original version of the upcoming Galaxy `19.09` software release. A pre-release version was installed at Galaxy Main https://usegalaxy.org for integration testing (in part to identify/fix corner-case issues like this one). 

The inability to permanently delete (purge) older analysis to make room for new analysis has impacted several end users. Some have now exceeded quota and are unable to proceed with their work. 

We have a solution and expect to have the quota recalculation correction applied to the server within the next few days. Even as administrators, we are unable to recalculate quotas correctly until the correction is applied to the server. We all need to wait for the fix.

**Details of the change.** Note that the development change (PR) will likely close out before the changes are actually applied to the usegalaxy.org server: https://github.com/galaxyproject/galaxy/pull/8773

**This summary ticket will update with ongoing status.** If by Monday, 10/14/2019, or after the situation is marked as resolved (this issue closes), and you are still having quota recalculation problems, please feel free to write to us at galaxy-bugs@lists.galaxyproject.org from your registered account email address. **First, be sure to confirm that your data purges are complete/correct and log out/back in again.** 

FAQs https://galaxyproject.org/support/
* [The account usage quota seems incorrect](https://galaxyproject.org/support/account-quotas/)
* [Checking for active vs deleted vs permanently deleted (purged) datasets and histories](https://galaxyproject.org/learn/managing-datasets/#delete-vs-delete-permanently)

Thank you for your patience while we restore this vital functionality.

**Comment by jennaj** [comment]
Not working. Quota claims to reset in admin gui but is not permanent. An example user's account still stays the same as before recalculating.

**Comment by jennaj** [comment]
Linked PR: https://github.com/galaxyproject/galaxy/issues/8771

Testing again

**Comment by dannon** [comment]
@jennaj The latest PR is https://github.com/galaxyproject/galaxy/pull/8778, which will make the recalculate via admin work correctly again.

**Comment by natefoo** [comment]
Main has been updated.

**Comment by erasche** [comment]
Sorry for the trouble y'all.

**Comment by jennaj** [comment]
Works at https://usegalaxy.org (User > Admin).

Np @erasche :) Glad we sorted it all out. 

@natefoo @dannon Can we close this out now?
