### ISSUE TITLE
run jobs in singularity containers

### ISSUE THREAD

**Issue by martenson** [galaxyproject/usegalaxy-playbook#262]
extracted from https://github.com/galaxyproject/usegalaxy-playbook/issues/118

from @natefoo:

I want to run all jobs in containerization for security purposes, but as written, the singularity/docker resolvers expect to be able to either find or build the images for the requirement sets of any tools sent to those destinations. That's not going to be possible for old tools. Instead, what I want for old tools is to have a destination that is configured to instruct Galaxy to use Singularity, but to not attempt to resolve dependencies with it. Then, I could create a "legacy Galaxy environment" Singularity image with the required deps we'd specified back in the Tool Shed dependency days, and another fairly basic image for Conda deps. Old tools could be sent to these destinations, and the regular non-container dependency resolution would be used for these, but they'd still run in containers.

**Comment by martenson** [comment]
From another note: Certain tools are/were writing their intermediary/backup files in our database/ folder (e.g. dataset_24424010.dat.bak). This is our design that allows this but potentially a huge problem.

**Comment by bgruening** [comment]
@martenson we do have the same aim. Please let me know if we should organize a call and discuss strategies and experiences. We do have a few tools running in Singularity already as a testbed.

**Comment by natefoo** [comment]
This can be closed. We're running older tools using a conda-in-singularity approach, currently via the job router but this is migrating to TPV. For reference, [here is EU's conda-in-singularity TPV destination](https://github.com/usegalaxy-eu/infrastructure-playbook/blob/1202d2fefb3d76dc071dba45df37dabfa18d45d6/files/galaxy/tpv/destinations.yml.j2#L333)
