### ISSUE TITLE
RNA-Star 2.6.0b does not lists out indexed genomes on the tool form at usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#266]
New as of about a week ago (tool update).

 * 2.6.0b is the most current version in MTS. It requires some tuning. Hiding from accessible tools for now at usegalaxy.org.
  * 2.6.0b-1 +  2.6.0b-0 both list out genomes properly and are now the versions available at usegalaxy.org.
 * 2.6.0b is loaded and functional at usegalaxy.eu

Related PRs
https://github.com/galaxyproject/tools-iuc/pull/2359
https://github.com/galaxyproject/tools-iuc/pull/2637#issuecomment-547977371

Reported at: https://help.galaxyproject.org/t/why-are-there-no-available-reference-genomes-in-rna-star/2387

**Comment by martenson** [comment]
per https://toolshed.g2.bx.psu.edu/view/iuc/rgrnastar/850f3679b9b4 `2.7.2b` is the latest version

**Comment by wm75** [comment]
yes, replace 2.6.0b with 2.7.2b above.
The 2.7.2b version has a couple of issues which will be fixed in an upcoming 2.7.3 version -> https://github.com/galaxyproject/tools-iuc/pull/2648

**Comment by wm75** [comment]
>     * 2.7.2b is loaded and functional at usegalaxy.eu

Only because @bgruening moved ref genomes manually to the right place

**Comment by natefoo** [comment]
I uninstalled 2.7.2b on usegalaxy.org, we'll upgrade in three steps:

1. Install the updated DM on test.galaxyproject.org. I think that may already be possible since galaxyproject/tools-iuc#2637 is merged.
1. Build all the desired 2.7.x indexes on test-datamanager, deploy to data.galaxyproject.org CVMFS repo.
1. Update to 2.7.3a (or later) on usegalaxy.org.

**Comment by jennaj** [comment]
**Ongoing Q&A at Galaxy Help about RNA-Star:** 
* Consolidated into this post: https://help.galaxyproject.org/t/rna-star-reference-genome/3156

**Notes for End-users:** 
* We are still working to resolve the various issues. 
* Most _Technical_ updates will post here.
* Please review the Q&A at Galaxy Help for updates about usage options and related. 
* Usage status is also currently included in the top banner message at usegalaxy.org.
