### ISSUE TITLE
process updating MTS is broken

### ISSUE THREAD

**Issue by martenson** [galaxyproject/usegalaxy-playbook#274]
possibly because the inventory has been switched from radegast to jetstream(?)

https://github.com/galaxyproject/usegalaxy-playbook/commit/ea0e690af12b4ab1a493a11fb21d2a57f7481089#diff-ff26bdaa2061dd18a5ad8817134dc789R29-R35

**Comment by natefoo** [comment]
Unbroken in 054faadc767f81a6cfd0fec93baddd66ac41c9e4
