### ISSUE TITLE
Retest tools once NCBI's `tbl2asn` binary issues resolved and on main

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#279]
https://github.com/bioconda/bioconda-recipes/pull/19790

**Comment by jennaj** [comment]
not exactly sure will apply the resolved issue, @natefoo as a global server dependency? Or do individual tools need to be updated?

**Comment by almahmoud** [comment]
I updated https://github.com/galaxyproject/usegalaxy-tools/pull/98/files to add just the newest version that works out of the box with the newest conda dependency. The old ones will still need to likely be patched so we don't drop the versions, but this will at least add a working `prokka` on Main for the time being

**Comment by natefoo** [comment]
I'll trigger that PR and update tbl2asn in the existing envs when galaxyproject/usegalaxy-tools#112 finishes. Thanks @almahmoud!

**Comment by natefoo** [comment]
Prokka 1.14.5 is now installed on usegalaxy.org, and I've fixed tbl2asn for the older versions (1.12 and 1.13) for another year.

**Comment by jennaj** [comment]
May be related -- some new errors reported -- I'm testing again: https://github.com/galaxyproject/usegalaxy-playbook/issues/318

**Comment by natefoo** [comment]
I installed tbl2asn-forever in all the prokka conda envs so this wasn't supposed to happen again. ;(
