### ISSUE TITLE
GATK 1.4 tools -- updated all after MTS is updated to run these in a Py2 env

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#281]
https://github.com/galaxyproject/tools-devteam/issues/546

**Comment by jennaj** [comment]
Workaround for End-Users

**It is strongly recommended to use updated variant analysis methods** 

See the GTN Tutorials: https://training.galaxyproject.org/training-material/topics/variant-analysis/

_Note: All GATK tools wrapped for Galaxy should be avoided or expect problems._: GATK 1.4 tools have been deprecated for several years. They remain on the usegalaxy.org server for backward compatibility reasons. There is some work to create wrappers for GATK4 tools but that is still a work in progress. Any GATK 2 or 3 release tools, that may be wrapped in the ToolShed (usegalaxy.org/toolshed) or found at other public Galaxy servers, are all considered deprecated/problematic to some degree.

**Comment by natefoo** [comment]
This should now be fixed. There's no tool update, the fix was some clever job running hackery by @mvdbeek in #288.

**Comment by jennaj** [comment]
Note for end-users:

Again, **all GATK 1.4 tools are deprecated and should be avoided**. Several have known issues unrelated to this particular correction. Your job may not even fail, but instead, produce putatively "successful" results are _scientifically incorrect_. 

**It is strongly recommended to use updated variant analysis methods**

See the GTN Tutorials: https://training.galaxyproject.org/training-material/topics/variant-analysis/
