### ISSUE TITLE
Annovar -- complete fixup for Py3 on Main

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#284]
**Annovar** as installed at Galaxy Main https://usegalaxy.org:

1. ANNOVAR Annotate VCF with functional information using ANNOVAR (Galaxy Version 0.2)
1. Was not Py3 compatible. Wrapper updated. MTS not (yet?).
1. Has licensing concerns... (brought up by Marius)
1. Plan? Update MTS, update Main, then mark as deprecated the tool panel?

**Tool Repo ticket** with more details: https://github.com/galaxyproject/tools-devteam/issues/539

**Tool Repo**: https://github.com/galaxyproject/tools-devteam/tree/master/tools/table_annovar

**MTS**: https://toolshed.g2.bx.psu.edu/view/devteam/table_annovar/08b003ee9db7 (doesn't appear to have been updated with most recent change? 

cc @mvdbeek @nekrut @natefoo

**Comment by natefoo** [comment]
This should now be fixed by the fix referenced in #288.
