### ISSUE TITLE
GALAXY_VIRTUAL_ENV python 2 destination for legacy tools

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/usegalaxy-playbook#288]
It hit me this morning that we could map tools that are currently failing because they're not python 2 compatible to a destination that sets `GALAXY_VIRTUAL_ENV` to a python 2 virtualenv with galaxy's internals. Of course we should fix whatever tool we can, but some tools aren't updatable because the dependencies are not in Conda, not even downloadable or have weird licenses.

If that works OK and saves us some trouble we could extend that on the Galaxy side where we could maintain a list of tool ids and versions, so that old tools continue working (by being mapped to a python 2 destination) and new tools need to be python 3 ready.

**Comment by jennaj** [comment]
+100 very very good idea. I remember you bringing this up (or @natefoo?) a few weeks ago, or something like it, and though very good idea then too. Good to have it on a ticket!

Agree so many involve older or un-upgradable tools. It creates a LOT of "noise". So selfishly voting YES. All the errors must be very frustrating for our users too of course.

Let's get things working now and sort through that list at a rational pace while granting our users a better intermediate experience while it is done :)

**Comment by jennaj** [comment]
Example problematic tool with dependency issue (are more): 

> tool id: join1
> tool version: 2.1.3
> 
> job stderr:
> Traceback (most recent call last):
>   File "/cvmfs/main.galaxyproject.org/galaxy/tools/filters/join.py", line 19, in <module>
>     from galaxy.util import stringify_dictionary_keys
> ModuleNotFoundError: No module named 'galaxy'

ping @natefoo -- if this is a distinct problem, we should clarify that and move to a different ticket. Hard to tell what is Py 2-3 related and what is just a general dependencies issue related to other updates. 

Many many user reports involving Text Manipulation tools -- are heavily used in tutorials -- bugs, Ghelp, etc.

**Comment by mvdbeek** [comment]
That's different, I promised Nate a script but as usual stuff came up. But at least the script will be done today.

**Comment by jennaj** [comment]
Cool -- thanks for clarifying. Making ticket for it, will link back. 

Linking a related that seems to be true. Yes, the entire tool suite is deprecated but still have users that prefer it. Needs Py2 env. https://github.com/galaxyproject/usegalaxy-playbook/issues/281

**Comment by mvdbeek** [comment]
Something like https://gist.github.com/mvdbeek/8ca744f5ee8f61bcb74faa8e35a147ff should work. Feasible for usegalaxy.org, @natefoo ?

**Comment by natefoo** [comment]
I tried it with StructureFold Iterative Mapping and it worked!

**Comment by natefoo** [comment]
Can you think of a way to generate a list of these tools?

**Comment by mvdbeek** [comment]
Hmm, that is a bit more difficult. I guess those tools in repos that still contain tool_dependencies.xml files would be a good guess. That catches more tools than necessary, but if this method works I don't think it would do much harm.

**Comment by mvdbeek** [comment]
https://gist.github.com/mvdbeek/590213f65520c498321e1850ed8d44e6 is a script that checks the toolbox for tools that use packages, https://gist.github.com/mvdbeek/24c9147d3a619f868374cfd379383a96 is the result of this script

**Comment by mvdbeek** [comment]
Should be fixed with https://github.com/galaxyproject/usegalaxy-playbook/commit/7e1981afbd43f55da669619b45679bb730ace391, thanks @natefoo. I think this is a nice one for reproducibility!
