### ISSUE TITLE
rna_star seems to need more memory

### ISSUE THREAD

**Issue by martenson** [galaxyproject/usegalaxy-playbook#29]
after the last move it spiked to 

```
 93 | toolshed.g2.bx.psu.edu/repos/iuc/rgrnastar/rna_star/2.5.2b-0
```

from 

```
 31 | toolshed.g2.bx.psu.edu/repos/iuc/rgrnastar/rna_star/2.5.2b-0
```

ping @natefoo

**Comment by natefoo** [comment]
It is using a [dynamic rule](https://github.com/galaxyproject/usegalaxy-playbook/blob/7c21a8e8e511076c9d71d46f9a518815de1874ff/env/common/files/galaxy/dynamic_rules/multi_dynamic_walltime.py#L141). With the additional logging I've just added, it should be fairly easy to fine tune the rule once we collect more failures.

**Comment by jennaj** [comment]
Closing, think we've bumped this up as far as it can go. Daily counts for this tool's memory failures are much lower now.
