### ISSUE TITLE
Roary 3.13.0 fails at usegalaxy.org -- likely installation issue

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#293]
**Tool:** `Roary the pangenome pipeline - Quickly generate a core gene alignment from gff3 files (Galaxy Version 3.13.0)`

**Workaround for end-users:** Until the tool is corrected at usegalaxy.org and this ticket closes out, it can be used instead at usegalaxy.eu. 

**Troubleshooting:** seems to have three problems
1. working directory path is maybe incorrect?
1. missing a datatype? ("dot")?
1. error help reports that "duplicated inputs were used" -- they weren't

**Test histories**: use some of the tutorial data from here: https://training.galaxyproject.org/training-material/topics/assembly/
* Fail: https://usegalaxy.org/u/jen/h/test-prokka-roary-gtn-tutorial
* Success: https://usegalaxy.eu/u/jenj/h/test-prokka-roary-gtn-tutorial 

**Error for the usegalaxy.org test.** Is the same as reported at Galaxy Help here: https://help.galaxyproject.org/t/roary-fatal-error-exit-code-2/3164

> Dataset Error
> An error occurred while running the tool toolshed.g2.bx.psu.edu/repos/iuc/roary/roary/3.13.0.
> 
> Error Details
> Execution resulted in the following messages:
> 
> Fatal error: Exit code 2 ()
> Tool generated the following standard error:
> 
> Use of uninitialized value in require at /cvmfs/main.galaxyproject.org/deps/_conda/envs/__roary@3.13.0/lib/site_perl/5.26.2/x86_64-linux-thread-multi/Encode.pm line 61.
> Usage: extract_proteome_from_gff [options] *.gff
> Take in GFF files and create FASTA files of the protein sequences
> 
> Options: -o STR    output suffix [proteome.faa]
>          -t INT    translation table [11]
>          -f        filter sequences with missing data
>          -v        verbose output to STDOUT
>          -d STR    output directory
>          -w        print version and exit
>          -h        this help message
> 
> For further info see: http://sanger-pathogens.github.io/Roary/
> Usage: extract_proteome_from_gff [options] *.gff
> Take in GFF files and create FASTA files of the protein sequences
> 
> Options: -o STR    output suffix [proteome.faa]
>          -t INT    translation table [11]
>          -f        filter sequences with missing data
>          -v        verbose output to STDOUT
>          -d STR    output directory
>          -w        print version and exit
>          -h        this help message
> 
> For further info see: http://sanger-pathogens.github.io/Roary/
> Cant open file: /galaxy-repl/main/jobdir/027/303/27303938/working/out/Sx2fKLLwy8/Prokka on data 11: gff.gff.proteome.faa
> Galaxy job runner generated the following standard error:
> 
> WARNING:galaxy.model:Datatype class not found for extension 'dot'
> WARNING:galaxy.model:Datatype class not found for extension 'dot'
> WARNING:galaxy.model:Datatype class not found for extension 'dot'
> WARNING:galaxy.model:Datatype class not found for extension 'dot'
> WARNING:galaxy.model:Datatype class not found for extension 'dot'
> WARNING:galaxy.model:Datatype class not found for extension 'dot'
> WARNING:galaxy.model:Datatype class not found for extension 'dot'
> WARNING:galaxy.model:Datatype class not found for extension 'dot'
> WARNING:galaxy.model:Datatype class not found for extension 'dot'
> WARNING:galaxy.model:Datatype class not found for extension 'dot'
> Detected Common Potential Problems
> The tool was executed with one or more duplicate input datasets. This frequently results in tool errors due to problematic input choices.

ping @davebx @mvdbeek @natefoo

**Comment by natefoo** [comment]
It's unclear to me what's broken here but apparently the [Perl error is not the problem](https://github.com/sanger-pathogens/Roary/issues/323).

**Comment by natefoo** [comment]
One thing that stands out: why does the tool wrapper copy its inputs? Are symlinks not sufficient?

```console
cp '/galaxy-repl/main/files/038/407/dataset_38407948.dat' 'Prokka on data 5: gff.gff' &&  cp '/galaxy-repl/main/files/038/411/dataset_38411630.dat' 'Prokka on data 11: gff.gff' &&   roary -f out -p ${GALAXY_SLOTS:-1} -e -n -i '95' -cd '99.0' -g '50000'  -t '11' -iv '1.5'  'Prokka on data 5: gff.gff' 'Prokka on data 11: gff.gff'
```

@takadonet any thoughts? Looks like you originally implemented the input handling.

**Comment by Takadonet** [comment]
Reason being is that Roary will follow the softlink and use that file name instead of the soft link name. All names would be **dataset_###**

**Comment by natefoo** [comment]
Ahhh gotcha. Blech, ok, thanks.

**Comment by natefoo** [comment]
Ah, it's not handling spaces in the input filenames:

```
Error: Cant access file /galaxy-repl/main/jobdir/027/303/27303938/working/Prokka
Error: Cant access file /galaxy-repl/main/jobdir/027/303/27303938/working/Prokka
```

**Comment by Takadonet** [comment]
Probably. That is my mistake assuming that file name would be command line friendly.

**Comment by natefoo** [comment]
They're quoted, though, so I think roary is not reading those params correctly?

**Comment by Takadonet** [comment]
Roary cannot handle them.

**Comment by natefoo** [comment]
@bgruening did you fix this manually somehow on usegalaxy.eu?

**Comment by bgruening** [comment]
I don't think so.

```
(venv) galaxy@sn04:~/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/roary/e02e9af2743f/roary$ hg diff
(venv) galaxy@sn04:~/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/roary/e02e9af2743f/roary$ 
```

**Comment by jennaj** [comment]
Thanks all. I can avoid the problem if the spaces are removed from the input dataset's actual name (set by the user, or by the upstream tool). See the original test history at usegalaxy.org if interested. I had copied the usegalaxy.org test over to usegalaxy.eu and simplied the dataset names .. that is why the tool worked at one server and not the other. Unexpected, since we normally avoid using GUI-editable file names ("labels") in code. Glad we isolated the problem!

The upstream tool commonly used (Prokka), when executed in Galaxy, will always insert spaces into the result dataset names that are later used as inputs to Roary. Meaning, hitting the bug will not be uncommon.

> **Workarounds for end-users until fixed:** 
* If executing tools from the History: Click on the pencil icon for an input `gff` dataset to reach the Edit Attributes forms. On the first tab, modify the file name, removing any spaces, then save. Do this for all `gff` inputs to avoid the bug. Rerun **Roary** using those renamed inputs.
* If executing tools from a Workflow: The output `gff` dataset generated by an upstream tool (likely **Prokka**) can be renamed to remove spaces as a "post job action" within the Workflow itself. This will pass the renamed `gff` inputs to **Roary** and avoid the bug.

**Comment by jennaj** [comment]
Tool version is now at **3.13.0+galaxy2**

* Change to avoid whitespace-in-name issue https://github.com/galaxyproject/tools-iuc/commit/40335305f3461201b017380c60c4c96c7e07322f#diff-82ce1a6d632f73cca872d8381a22d0db7ba3536082eaf7d8a4edd5bb8642e3f9R17
* Dev repo https://toolshed.g2.bx.psu.edu/view/iuc/roary/91887494eb97
* Toolshed repo https://github.com/galaxyproject/tools-iuc/commits/main/tools/roary
