### ISSUE TITLE
Dependency issue with main galaxy tool- tRNA_prediction

### ISSUE THREAD

**Issue by herbercr** [galaxyproject/usegalaxy-playbook#301]
Problem:

Tools errors in python script. All dependencies are installed, specifically biopython in which the error occurs with no module found. 

Tool:

https://toolshed.g2.bx.psu.edu/view/bgruening/trna_prediction/358f58401cd6

Error:
`Traceback (most recent call last):
  File "/mnt/c/galaxy/database/shed_tools/toolshed.g2.bx.psu.edu/repos/bgruening/trna_prediction/358f58401cd6/trna_prediction/tRNAscan.py", line 7, in <module>
    from Bio import SeqIO
ModuleNotFoundError: No module named 'Bio'`

**Comment by herbercr** [comment]
The python script runs outside of galaxy as well

**Comment by natefoo** [comment]
Is this an issue on usegalaxy.org? The path to the tool (`/mnt/c/galaxy/...`) is not something in use on our server.

**Comment by jennaj** [comment]
Hi @herbercr 

Should this tool still be problematic at your server, please test to see if you can reproduce the dependency issue (using your data and parameter choices) at **Galaxy EU https://usegalaxy.eu**. This tool is installed at that particular public server, and that server also happens to be administrated by the tool author: @bgruening

* _If not reproducible at that server_:
  * The most current version of any tool is usually the best choice.
  * Running the most current version of Galaxy itself is also best. Check and update if needed.
  * Re-install the tool _after_ updating Galaxy to see if that resolves the issue.
  * Allow Galaxy to manage the dependencies unless you have a specific reason not to. If you decide not to, then you'll need to troubleshoot why the dependencies are not linked. If you get stuck -- you can follow up in the issue your created at the tool repository https://github.com/bgruening/galaxytools/issues/1005. The current issue description does not have enough details yet. Or, maybe these are both orphan issues, and this was resolved (?). 

* _If reproducible at that server_:
  * Please update the current issue at the tool wrapper's Github repository.
  * You can reference this issue in that new issue for context.
  * Including a shared link to a small history with an example of the error can usually help. This would be publically accessible.
  * To share the error example with the tool author/server admin privately, one alternative is to submit a bug report from the error at usegalaxy.eu. Note that you sent in a bug report in the issue description -- they'll know how to link those up. 

Next time, when you are having an administration problem linked to a particular tool at your own local server, these same steps would apply for most cases. This particular repository is for tracking issues at usegalaxy.* servers. Problems with tools that are not reproducible at a public server that hosts the tool are best directed to our **Gitter channel https://gitter.im/galaxyproject/Lobby** or the **Galaxy Help forum https://help.galaxyproject.org**. Including details about your server's configuration and your dependency management choices is useful for context. A Github issue at the tool's repository is also Ok for some cases, but you'll need to provide more details, including the outcome of the test to check if reproducible or not at a public server (when possible). 

Thanks!

**Comment by jennaj** [comment]
Closing here, not an issue with usegalaxy.org/usegalaxy.*

See: https://github.com/bgruening/galaxytools/issues/1005
