### ISSUE TITLE
Cannot open usegalaxy.org anymore

### ISSUE THREAD

**Issue by sarmisthan** [galaxyproject/usegalaxy-playbook#305]
Hello, I was analysis for dome DNA seq data, so close to be done. Now cannot open . I was doing bowtie 2. Then the error showed on the main screen as in middle panel in pink background. Fatal error cannot update. Contact the administrator. Please help since I need those bam files for our grant.

**Comment by bgruening** [comment]
@sarmisthan thanks for the notification. We will work on it and hopefully, it will be back soon.
