### ISSUE TITLE
RNA STAR fails on certain indeces

### ISSUE THREAD

**Issue by martenson** [galaxyproject/usegalaxy-playbook#310]
C elegans https://help.galaxyproject.org/t/error-with-star/4409
Drosophila dm6 https://help.galaxyproject.org/t/rna-star-dynamic-rule-error/4649

cc @jennaj

**Comment by jennaj** [comment]
The indexes are fixed now -- including these two https://github.com/galaxyproject/usegalaxy-playbook/issues/306
