### ISSUE TITLE
When will HISAT be included in tool_data_table_conf.xml ?

### ISSUE THREAD

**Issue by chambm** [galaxyproject/usegalaxy-playbook#32]
Currently having to add this in manually:
https://github.com/galaxyproject/usegalaxy-playbook/blob/master/files/galaxy/usegalaxy.org/config/tool_data_table_conf.xml
But since main has moved to recommending HISAT, this seems odd (probably out of sync).

**Comment by natefoo** [comment]
It's in [shed_tool_data_table_conf.xml](https://github.com/galaxyproject/usegalaxy-playbook/blob/7c21a8e8e511076c9d71d46f9a518815de1874ff/env/main/files/galaxy/var/shed_tool_data_table_conf.xml).
