### ISSUE TITLE
Deploy Jupyter GxIT on usegalaxy.org

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/usegalaxy-playbook#326]

**Comment by natefoo** [comment]
Stuff in the playbook:

**Comment by natefoo** [comment]
Stuff in the playbook:
- Job and job router conf
- Galaxy-side proxy supervisor config
- Tool conf

Stuff not in the playbook:
- Galaxy-side proxy clone and node setup
- k8s-side proxy setup
- Anything to automatically determine the k8s-side proxy container's IP
