### ISSUE TITLE
Add JBrowse to sanitize_allowlist

### ISSUE THREAD

**Issue by abretaud** [galaxyproject/usegalaxy-playbook#333]
Hi!
It would be great to add jbrowse to the "Tool Sanitization Allowlist" on usegalaxy.org. Currently it's impossible to visualize the results, while it's used in several GTN tutorials.

xref https://help.galaxyproject.org/t/jbrowse-error-when-i-want-to-visualize-the-results-of-snp/3407

(Don't know if it's the best place for this)

**Comment by natefoo** [comment]
This is the best place!

All versions of JBrowse currently installed on usegalaxy.org are now allow-listed, can you try again?

Thanks!

**Comment by abretaud** [comment]
Thanks! it works now :+1:
