### ISSUE TITLE
Kraken is failing for memory at http://usegalaxy - increase allocation?

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#34]
Many recent bug reports for the tool failing on reasonably sized datasets (1G, 2280280 FASTQ reads and larger).

ping @natefoo

**Comment by natefoo** [comment]
Can we make a reasonable guess as to the memory requirements of the tool based on inputs and/or parameters? It currently already gets the standard 30GB allocation for all multicore tools.

**Comment by jennaj** [comment]
I think we can close this. I haven't seen a memory problem reported in a very long time now. Maybe something else was going on rather than the mem allocation that is now configured differently and/or fixed.
