### ISSUE TITLE
Update Circos tool suite at usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#346]
> Workaround for End-Users:
> 
> Please try the latest version of the tool at **usegalaxy.eu**: Circos visualizes data in a circular layout (Galaxy Version ~~0.69.8+galaxy8~~ `0.69.8+galaxy10`). Avoid earlier versions if using "Circos Presets" for Karyotype.

Problem reported/confirmed 10/27/21
Galaxy Help post: https://help.galaxyproject.org/t/circos-functional-on-usegalaxy-eu-but-not-usegalaxy-org/6972

Test histories (GTN [test data](https://training.galaxyproject.org/training-material/topics/visualisation/tutorials/circos/tutorial.html#ideogram-1))
* https://usegalaxy.org/u/jen-galaxyproject/h/test-circos
* https://usegalaxy.eu/u/jenj/h/test-circos

cc @davebx 

~~MTS: https://toolshed.g2.bx.psu.edu/view/iuc/circos/7f13dc906cb9~~

More context
* ~~The prior version `0.69.8+galaxy7` works fine at EU but not at ORG, so there is probably more going on than just the need to update to the latest wrapper. Maybe the dependencies for `0.69.8+galaxy8` and `0.69.8+galaxy7` are the same (?) and updating to the latest runtime container environment will address both. Perhaps @hexylena has some insight around that.~~
* *Upgrading to `0.69.8+galaxy10` should resolve all known issues*. See tool repo history here: https://github.com/galaxyproject/tools-iuc/commits/master/tools/circos

**Comment by jennaj** [comment]
Current version is now: `0.69.8+galaxy10`

MTS: https://toolshed.g2.bx.psu.edu/view/iuc/circos/290a11559985

Note: Includes at least one other distinct bug fix ("Chrom presets" wasn't functional anywhere, any version version `0.69.8+galaxy7` or later)
<img width="711" alt="circos_Presets" src="https://user-images.githubusercontent.com/8999735/144086673-63351b22-05bf-4fe1-ab10-2889474f5b49.png">

**Comment by jennaj** [comment]
Fails tests: https://github.com/mvdbeek/usegalaxy-tests/issues/26

@bgruening @hexylena -- what version of the tool should we update to?

`.org` is at 0.69.8+galaxy7 (known issue re karyotype index, but doesn't impact GTN tutorial afaik)
`.eu` is at 0.69.8+galaxy9
`mts` is at 0.69.8+galaxy10

cc @davebx

**Comment by hexylena** [comment]
please update to galaxy10 @jennaj

**Comment by jennaj** [comment]
Thank you and apologies for posting in the matrix chat about the same question!! 

We can try get this updated before Monday if possible. If more delays, I think we should add to the visualisation_circos's tutorial channel in the pinned FAQ to run at `eu` or `au` instead.

**Comment by jennaj** [comment]
Didn't actually install. Not sure why.

**Comment by jennaj** [comment]
Not sure what we need to do. Can you help @hexylena? 

The version sorting isn't working correctly when loaded from the tool panel (defaults to the 7 version, not the new 10 version). And the tool is failing for what looks like the original karyotype issue.

https://usegalaxy.org/u/jen/h/test-history-circos

**Comment by dannon** [comment]
@jennaj The tool version sorting is being looked into by @natefoo; he has some work in progress that will resolve this.

**Comment by jennaj** [comment]
Great, thank you!

I'm going to close out the open tickets -- the tool runs whoohoo

**Comment by hexylena** [comment]
@jennaj do you have a still failing circos history, I think I've recently seen one potential cause of the specific failure and I want to check.
