### ISSUE TITLE
Datatype problem with CONVERTER_Bam_Bai_0

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#36]
Server: main https://usegalaxy.org
Galaxy version: 17.05, commit 1d485390b0af80441c4e577f8fb7ddde265f9618
Function: edit attributes > convert > bam to bai
Galaxy Tool ID: CONVERTER_Bam_Bai_0
Galaxy Tool Version:  1.0.0
Bug reports: sent 9/10 + 9/11 have examples
Error: 
> red dataset with WARNING:galaxy.model:Datatype class not found for extension 'bai'

**Comment by natefoo** [comment]
This converter was removed in galaxyproject/galaxy#4598
