### ISSUE TITLE
Export to FTP is still "possible"

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/usegalaxy-playbook#362]
> This Galaxy server allows you to upload files via FTP. To upload some files, log in to the FTP server at ftp://usegalaxy.org using your Galaxy credentials. For help visit the [tutorial](https://galaxyproject.org/ftp-upload/).

I guess we should disable this ? This is via the history export dialog.

**Comment by natefoo** [comment]
This is gone now with the removal of the ftp options in 76b3bae83e7b4945e0b306d16c3b1cab2de7cf6e.
