### ISSUE TITLE
Update "Join two Datasets" tool once fixed, in release, and applied to main (fixes tabular datatype set in output)

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#46]
Join two Datasets side by side on a specified field (Galaxy Version 2.1.0 && 2.1.1)

_This breaks the 101 tutorial_ https://galaxyproject.org/tutorials/g101/#recovering-exon-info-and-displaying-data-in-genome-browsers

Example history: https://usegalaxy.org/u/jen/h/copy-of-courseegexons-and-repeats

The other Join tool works fine.

**Comment by natefoo** [comment]
I believe this was fixed with galaxyproject/galaxy#4745

**Comment by jennaj** [comment]
There are still inconsistencies in the datatype assignment.

 - The data is now getting sniffed as BED when output from this tool (bed12 variant) when it really should be just TABULAR or rather INTERVAL (doesn't fit BED spec). Example: dataset 9

 - If "autodetect" is run through Edit Attributes on that same output (dup of dataset 9), `bed` is retained. Example: dataset 10

 - If the same content is uploaded via paste (first few lines) and sniffed with the Upload tool, `interval` is assigned - and that is correct and more specific than `tabular`. Example: dataset 11

 - If the same content is uploaded via paste (first few lines) and sniffed with the Upload tool, `interval` is assigned (dup of dataset 11). Running "autodetect" on it after retains the `interval` format. Example: dataset 12

 - If the same content is uploaded via URL (dataset 9 or 10 download link, includes ALL lines) and sniffed with the Upload tool, `interval` is assigned. Example: dataset 13.

 - If the same content is uploaded via downloaded/uploaded browsed file (dataset 9 or 10 downloaded data, includes ALL lines) and sniffed with the Upload tool, `interval` is assigned. Example: dataset 14.

There are more variations that could be tested  - but this is probably enough to figure out what is going on. I didn't expect Autodetect and Upload to sniff different datatypes for the same exact data - that seems like a bug.

The tutorial will work on this data when assigned to BED, but any other operations/tools that consume BED format will fail. Also -- since this is part of a tutorial, having this data assigned to bed is not teaching 101 learners what BED datasets should actually contain as valid content. 

> Chrom | Start | End | Name | Score | Strand | ThickStart | ThickEnd | ItemRGB | BlockCount | BlockSizes | BlockStarts
> -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
> chr22 | 16280333 | 16280411 | uc002zlh.1_cds_8_0_chr22_16280334_r | 0 | - | uc002zlh.1_cds_8_0_chr22_16280334_r | 1
> chr22 | 17586742 | 17586844 | uc002zly.4_cds_10_0_chr22_17586743_f | 0 | + | uc002zly.4_cds_10_0_chr22_17586743_f | 1

**Comment by natefoo** [comment]
Is this a change from the old behavior of the join tool, or just incorrect behavior by the join tool in general?

**Comment by jennaj** [comment]
This is new behavior for Join two Datasets. Originally outputted `tabular`, didn't try to inherit the datatype from the inputs (what seems to be the root problem). Should always be `tabular` for this tool, regardless of input datatypes.

Not sure if Autodetect vs Upload was a problem before, for this use case, but it is now. Should we put that in a distinct ticket?

**Comment by natefoo** [comment]
Auto-detect won't change datatypes right? It just detects metadata for the currently set datatype?

I guess I am unclear on whether this is a Main issue or a tool issue. It seems like the tool should be updated again to always output `tabular` as you say.

**Comment by jennaj** [comment]
Agree that this might be a tool problem exposed with the newer Galaxy release. 

Other tools now inherit datatype, and in most cases that is very useful. Is probably just a few legacy tools that have this problem. This will need a ticket - I'll do that and link it back.

As for Edit attributes/autodetect, maybe it should use the same sniffers as Upload. Most work correctly, the known sniffer problems are logged in tickets. Or - could offer the user a choice - 1) autodetect metadata for the existing datatype -- or -- 2) autodetect the datatype and then the associated metadata for that datatype. In short, a "do-over" and a version of file type validation currently only available via Upload.

Consistent data handling/sniffing would be less confusing for end-users imo, but we can see what others think. Personally, I think it re-sniffing would solve many (many) end-user input-related usage problems. 

If new sniffer bugs pop out, those should be fixed anyway. Yes? If agree, I'll open a ticket under /galaxy for review and prioritization. 

@guerler Thoughts on using Upload's sniffing as an option in Edit attributes?

**Comment by jennaj** [comment]
Ticket for Join Two Datasets: https://github.com/galaxyproject/galaxy/issues/6107

**Comment by qiagu** [comment]
How about change to `auto_format="true"`?

**Comment by jennaj** [comment]
@qiagu In a local from the primary dev branch I got today, the updated tool now assigns the `tabular` datatype, which is great! Join two Datasets side by side on a specified field (Galaxy Version 2.1.2)

Once Main gets that update, I'll retest there and we can close out that specific issue.

I don't see the sniff (now "change datatype") button. I probably didn't clone this right, trying again.

**Comment by qiagu** [comment]
By clicking the above link, you may notice that the adding sniff/detect button is in a different PR and still under review. Please wait a while unless you want to try the unmerged branch.

**Comment by jennaj** [comment]
The pencil icon changes to a lighter color, but doesn't open the edit attr forms. In both Chrome and Safari.

branch

$ git clone -b join1 https://github.com/qiagu/galaxy.git

error after clicking the pencil icon

<img width="792" alt="screen shot 2018-11-16 at 2 40 23 pm" src="https://user-images.githubusercontent.com/8999735/48651013-c5167f00-e9ad-11e8-950e-173a78669ac3.png">

**Comment by qiagu** [comment]
It works for me at local. The issue that the edit attr forms couldn't open probably doesn't relate to my PR. Yes, the unmerged branch is many commits behind. Please wait a while then.

**Comment by jennaj** [comment]
The PR got merged into dev by @jmchilton later on Friday.

 - I'll test to see if I can reproduce the problem now using that branch in a default local (in a vitualenv). 

 - We should probably also get the dev branch on Test updated, so we can see if reproducible there, might offer some insight about what, if anything, is still going wrong. 

Thanks! Autodetecting datatype, post-upload, is very useful functionality.

**Comment by jennaj** [comment]
@qiagu the new datatype sniff button works really well!

 - on bed data that is out of spec, will change to tabular
 - on a few variations of interval data (originally assigned to tabular), it will assign an interval in some cases and not others. The sniffer for interval could probably be improved, but that would be a lower priority and not part of this change/fix.

Let's push the PR to Dev, then update Test with it, to try it on a public server and see if we also get feedback from everyone else is working from the dev branch

**Comment by jennaj** [comment]
https://github.com/galaxyproject/galaxy/pull/7018

**Comment by jennaj** [comment]
Retest when 19.01 gets on Main @jennaj

**Comment by natefoo** [comment]
@jennaj Main's running 19.01 now.
