### ISSUE TITLE
Workflows fail to launch jobs for certain handlers

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#47]
Occurs at Galaxy Main https://usegalaxy.org

_Workaround pending_

Primary Biostars question https://biostar.usegalaxy.org/p/25048/

ping @dannon

**Comment by dannon** [comment]
Asked in IRC, but maybe it didn't relay.  Are you still seeing this?  The 'new' stuck workflows had cleared when I checked this morning after handler restarts.

**Comment by jennaj** [comment]
Correct, this is now working, closing out.

**For Galaxy users:** IF you are sending your workflow to a new history, go to "Saved Histories" to find your new output.
