### ISSUE TITLE
Cuffdiff SQLite output problem

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#50]
Update to 2.2.1.5 (from early 2017, conda updated). The server currently has 2.2.1.3 (2015).

https://toolshed.g2.bx.psu.edu/view/devteam/cuffdiff/d3ae7d9c2202

Duplicated posts at Biostars about the issue have all been consolidated into this post. Use as the master when helping users. Should also post back an update once resolved: https://biostar.usegalaxy.org/p/26894/

@natefoo @davebx

**Comment by natefoo** [comment]
This is done on Test and Main.

**Comment by jennaj** [comment]
I didn't get to this today but will test Monday and close out if resolved. Thanks for updating!

**Comment by jennaj** [comment]
SQLite option alone does not produce the error and another param that I thought might be involved (mulit-read correct) turned out to not be. Might be a problem when used in combination with bias correction instead (GTF is a match in this test). Running the test, feedback once done.

**Comment by jennaj** [comment]
@natefoo Revised tests produce this

 - **SQLite option works with the earlier version 2.2.1.3**

- **SQLite option fails (alone) with latest version 2.2.1.5**

The same data was used with both versions. This looks like a tool problem but could possibly be config/dependencies.

Error:

```
.... bunch of the usual log file lines ....

There were 50 or more warnings (use warnings() to see the first 50)
Creating database ./cummeRbund.sqlite
Reading Run Info File ./run.info
Writing runInfo Table
Reading Read Group Info  ./read_groups.info
Writing replicates Table
Reading Var Model Info  ./var_model.info
Writing varModel Table
Reading ./genes.fpkm_tracking
Checking samples table...
Populating samples table...
Error: Column name mismatch.
In addition: There were 50 or more warnings (use warnings() to see the first 50)
Execution halted
```

**Comment by jennaj** [comment]
@nekrut @bgruening 

I noticed that Cuffdiff (and most Cuff* tools) are marked as deprecated at https://galaxy.uni-freiburg.de (all versions, including `2.2.1.5`). 

Should we remove Cuffdiff version `2.2.1.5` from https://usegalaxy.org?

And mark the earlier versions as deprecated? (Seem to work Ok)

Leaving the version that doesn't work on the main server is going to trigger more usage errors/bug reports. We have 9 so far sent to our bugs mailing list (since Feb 27th, when we updated) and a few other questions about the problem at Biostars (local use, public server use) that go back at least 4 months (the tool was last updated in the MTS about a year ago https://toolshed.g2.bx.psu.edu/view/devteam/cuffdiff/d3ae7d9c2202).

<img width="383" alt="screen shot 2018-03-07 at 3 20 56 pm" src="https://user-images.githubusercontent.com/8999735/37124017-5fbedfd0-221b-11e8-8821-d509f0f8acd5.png">

**Comment by bgruening** [comment]
@jennaj this deprecation warning was more a hint to our users that people should use other tools or get in contact with us. We do have some bad experience with cuff* and think people should use other tools if they can. However, a few users are still using them but we wanted to make clear that we will phase out these tools.

**Comment by jennaj** [comment]
@bgruening Ok, thanks! Then maybe the SQLite option not working is a https://usegalaxy.org problem. We've had that before and some config change @natefoo made fixed it. Looks like we need that again to get the tool fully functional. More bug reports have come in about this option/version - the latest was lasts night.

**Comment by jennaj** [comment]
ping @davebx @natefoo -- what is the status for the SQLite output fix? It might be the same as the prior correction for the same problem with earlier tool versions (problems were a server-side configuration issue if I am remembering correctly).

Thanks!

**Comment by jennaj** [comment]
Ignore the htseq link, mistake and unrelated.

Retesting Cummerbund again.

**Comment by natefoo** [comment]
Is there an updated version that fixes the SQLite output? If this is not a tool problem I am pretty unclear on what the issue is.

**Comment by martenson** [comment]
The Main server has the `Galaxy Version 2.2.1.5` which is the latest in the MTS.

**Comment by jennaj** [comment]
I opened at ticket at devteam repo - this has been a problem for a while now, maybe the tool itself is buggy if the MTS install is Ok.

https://github.com/galaxyproject/tools-devteam/issues/509

**Comment by jennaj** [comment]
devteam repo ticket updated -- tool still fails at ORG, testing at EU, details there

**Comment by jennaj** [comment]
Works at EU.

Is something different about the tool configuration? 

@abretaud also reported a problem at his Galaxy, so should share the solution with him. https://github.com/galaxyproject/tools-devteam/issues/509#issuecomment-416595816

**Comment by jennaj** [comment]
Tool has been deprecated, closing.
