### ISSUE TITLE
Generating a history share link does not always stay persistently in that state

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#51]
I'm having a problem with generating a share link (not publish) then having it revert to an unshared state. Been since `17.01`. Happened again today. Has anyone else run into this?

Doesn't happen every time could be tricky to track back and I'm not sure what would be important to share for troubleshooting (if anything). The java console logs don't seem to contain anything interesting.

Let me know what I should capture next time it happens.

**Comment by natefoo** [comment]
Has this still been happening?

**Comment by jennaj** [comment]
Last time was on Tues. Let's give it until mid-next week and if doesn't come up again, I'll close it out. We can always reopen if occurs after that. Thanks!

**Comment by jennaj** [comment]
Closing - can no longer reproduce. Thanks!
