### ISSUE TITLE
Update featurecounts from on main once in Tool Shed

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#52]
Originally: Update featurecounts from 1.4.6.p5 to 1.5.3 once in Tool Shed 

The earlier version can produce a "core dump" error under certain usage conditions. 

Users are reporting this error and it was a known bug in the prior version. The tool authors fixed it and the wrapper uses the new version. And like the wrapper has been updated so is probably close to being bundled and put in the MTS by the IUC. We'll want to update once in MTS.

 - Bug discussion with version impacted https://www.biostars.org/p/169712/
 - IUC ticket to wrap updated version https://github.com/galaxyproject/tools-iuc/pull/1515
 - MTS repo has 1.4.6.p5 has most recent as of today https://toolshed.g2.bx.psu.edu/view/iuc/featurecounts/de2c5e5a206c

ping @davebx @bgruening

**Comment by natefoo** [comment]
I've updated it to the latest (1.6.0.2) on both Test and Main.

**Comment by jennaj** [comment]
Thanks - looks like another update is coming to address some usage issues I found while testing the newer version. Not in MTS yet afaik. Will watch for it. Let's leave this open as a reminder.

**Comment by jennaj** [comment]
https://github.com/galaxyproject/tools-iuc/issues/1754

**Comment by jennaj** [comment]
PR for updates https://github.com/galaxyproject/tools-iuc/pull/1755

**Comment by martenson** [comment]
updated on Main in https://github.com/galaxyproject/usegalaxy-playbook/commit/34a4dd4815981e23ec7f3a436048cf990c3146ce

**Comment by jennaj** [comment]
version 1.6.0.3

**Comment by jennaj** [comment]
Works correctly with the built-in index for hg19. Test for using GTF from history in progress, and will reopen if that fails. Closing.

Test history: https://usegalaxy.org/u/jen/h/test-history-cufflinks-hisat2 (includes other sets - featurecounts in data 30-38)

**Comment by jennaj** [comment]
Problems found with later updates since this one done, tool need another update. Tracked here: https://github.com/galaxyproject/usegalaxy-playbook/issues/139
