### ISSUE TITLE
Update MultiQC to use the IUC version of the tool on main/test

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#53]
Currently installed 1.0.0.0: https://toolshed.g2.bx.psu.edu/view/engineson/multiqc/5e4080791d90

New IUC version 1.2.0: https://toolshed.g2.bx.psu.edu/view/iuc/multiqc/3bad335ccea9

Note that the install will require the tool be added to the HTML display whitelist: 
<img width="567" alt="screen shot 2017-10-26 at 12 28 01 pm" src="https://user-images.githubusercontent.com/8999735/32072931-45904070-ba49-11e7-8a1a-ab11741e5253.png">

ping @davebx but double check with @nekrut first as the form help is slightly different in the updated IUC version and this is included in a few tutorials - although the help section isn't really shown (including here https://galaxyproject.org/tutorials/ngs/#assessing-data-quality and in the related video)

There are some common usage issues with the tool and the error message is difficult to interpret (for users). Ticket against repo describing problem and potential solutions here: https://github.com/galaxyproject/tools-iuc/issues/1538

**Comment by natefoo** [comment]
This is done on Test and Main. The old version is still installed, but hidden.

**Comment by jennaj** [comment]
Test pass on Main, thanks!

Enhancements to help users input the correct data is still open, but I pinged on the ticket to see what the plan is https://github.com/galaxyproject/tools-iuc/issues/1538
