### ISSUE TITLE
Deseq2 dependency problem - missing tools/deseq2/deseq2.R ?

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#54]
Should this be reported at IUC (core tool issue) or is it really just a dependency problem?

**Tool at https://usegalaxy.org:** toolshed.g2.bx.psu.edu/repos/iuc/deseq2/deseq2/2.11.39

**Latest in MTS:** also 2.11.39 https://toolshed.g2.bx.psu.edu/view/iuc/deseq2/24a09ca67621

**Use case:** Input TMP files from Salmon and use option to provide annotation in "transcript - gene" format produces the error below. Including a GTF that lacks transcript features also triggers a similar error. 

**Error:**
```
Fatal error: An undefined error occurred, please check your input carefully and contact your administrator.
Warning messages:
1: multiple methods tables found for 'arbind' 
2: multiple methods tables found for 'acbind' 
3: replacing previous import 'IRanges::arbind' by 'SummarizedExperiment::arbind' when loading 'DESeq2' 
4: replacing previous import 'IRanges::acbind' by 'SummarizedExperiment::acbind' when loading 'DESeq2' 
reading in files
1 Error in tximport(txiFiles, type = "sailfish", tx2gene = tx2gene) : 
  tried but couldn't use reader() without error
  user will need to define the importer() as well
```

Is this the problem? 

1 Error in tximport(txiFiles, type = "**sailfish**", tx2gene = tx2gene) :

**Comment by jennaj** [comment]
Another test case using Salmon + Sailfish as input with a tx2gene tab works. Still not sure why original error comes up - the data inputs look fine.

**Comment by bgruening** [comment]
@jennaj do you still need help here? It does not look like a dependency problem, but like a wrong file.

**Comment by jennaj** [comment]
I think you are right about the inputs. I can't find anything wrong with them, but the workflow is several steps long which means a minor error could have been introduced somewhere along the path. Plus, I still cannot reproduce this with other test data, including the tutorial data. Am going to close it out for now and watch for future reports of issues.
