### ISSUE TITLE
Update Diffbind from 2.2.1 to 2.2.2 (in MTS)

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#56]
https://toolshed.g2.bx.psu.edu/view/bgruening/diffbind/6031247f61d4

**Comment by natefoo** [comment]
Diffbind 2.6.5.0 (previously not installed) has been installed on Test, and Diffbind has been updated to 2.6.5.0 on Main.

**Comment by jennaj** [comment]
Test job still running but would expect it to fail by now if there was a problem. I'll reopen if something odd pops out when done.

Test history: https://usegalaxy.org/u/jen/h/test-history-diffbind

(has another but cannot share it publically)

Thanks!!

**Comment by jennaj** [comment]
Ok -ran correctly and PDF graphic displays. Win!
