### ISSUE TITLE
allow running ts/galaxyplaybook even when the deployed version has changes

### ISSUE THREAD

**Issue by martenson** [galaxyproject/usegalaxy-playbook#6]
blow up only when conflicts happen?

**Comment by natefoo** [comment]
Local changes really ought to be committed to a local branch.

**Comment by martenson** [comment]
so if I branch out before making any local changes, then commit them, and then run playbook with updated revision ... what version will the galaxy be at? #master or my #new_branch?

**Comment by natefoo** [comment]
Up to you, you could merge back to #master, or merge #master to your branch.

**Comment by natefoo** [comment]
Probably should merge #master to your branch so that if/when your changes are in #master you can simply delete your branch.

**Comment by martenson** [comment]
thanks for the explanations @natefoo
