### ISSUE TITLE
Update Stringtie tools to new version

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#60]
The current version: StringTie transcript assembly and quantification (Galaxy Version 1.3.3)

Issue: Produces errors unless a very specific prep is done first. Reported as an usage error frequently. The newer version should fix that error use-case and has other improvements.

Tracking: Changes was finalized. Related tickets:

 - PR https://github.com/galaxyproject/tools-iuc/pull/1545
 - Issue https://github.com/galaxyproject/tools-iuc/issues/1322

Status: **Is not in MTS yet**, but expect it to be there soon. Both Stringtie tools should be updated if each has a new version.

**Comment by jennaj** [comment]
The updated version 1.3.3.1 is in the MTS as of 11/9 and could be updated on Test/Main. @davebx would you have time to do this? Thanks!

https://toolshed.g2.bx.psu.edu/view/iuc/stringtie/76d290331481

**Comment by martenson** [comment]
updated on Main in https://github.com/galaxyproject/usegalaxy-playbook/commit/34a4dd4815981e23ec7f3a436048cf990c3146ce

**Comment by jennaj** [comment]
Original test <poof!> may do over. Had too many tests going and then main updated and some are ... somewhere...

**Comment by jennaj** [comment]
Tests pass: https://usegalaxy.org/u/jen/h/test-history-stringtie-and-stringtie-merge-133 data 187-188. Many thanks!
