### ISSUE TITLE
Unicycler 0.4.1 failures

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#61]
**tool**

toolshed.g2.bx.psu.edu/repos/iuc/unicycler/unicycler/0.4.1

**error**

`Remote job server indicated a problem running or monitoring this job`

**test history** datasets 29-30 v 0.4.1, datasets 27-28 v 0.2.0

https://usegalaxy.org/u/jen/h/test-tools-prokka-unicycler-quast-multiqc

**prior issue** (v 0.2.0 failure, resolved 9/27/17)

https://github.com/galaxyproject/galaxy/issues/4516

ping @natefoo

**Comment by jennaj** [comment]
Update: A fix has been made and we are testing.

**Comment by natefoo** [comment]
Mine ran successfully, hopefully yours does too.

**Comment by jennaj** [comment]
Yes, mine finally went through and was a success as well. Thanks! Closing this out.

**For anyone following this fix that had problems, please also rerun now.** 

If for some reason the job errors, double check your inputs and submit a bug report if you cannot determine the failure reason. Please leave the inputs and outputs undeleted so we can troubleshoot.
