### ISSUE TITLE
Convert BIOM formats 2.1.5.0 dependency problem

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#63]
Tool: toolshed.g2.bx.psu.edu/repos/iuc/biom_convert/biom_convert/2.1.5.0

Error: 

> Fatal error: Exit code 127 ()
> /galaxy-repl/main/jobdir/017/540/17540870/tool_script.sh: line 9: biom: command not found

ping @davebx

**Comment by natefoo** [comment]
Version 2.1.5.0 of the biom-format suite (previously not installed) has been installed on Test, and the dependencies have been corrected on Main.
