### ISSUE TITLE
Request to add STAR Fusion tool to main

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#64]
MTS https://toolshed.g2.bx.psu.edu/view/iuc/star_fusion/0b44456754e2

Confirmed with IUC that the tool is ready and appropriate to be deployed on public servers. The https://galaxy.uni-freiburg.de server is also going to add it now (hadn't been requested earlier).

Thanks!

ping @davebx @nekrut

**Comment by martenson** [comment]
installed on Main in https://github.com/galaxyproject/usegalaxy-playbook/commit/34a4dd4815981e23ec7f3a436048cf990c3146ce

**Comment by jennaj** [comment]
Tested before, couldn't get it to work. Will try again.

**Comment by martenson** [comment]
available at https://usegalaxy.org/root?tool_id=toolshed.g2.bx.psu.edu/repos/iuc/star_fusion/star_fusion/0.5.4-3+galaxy1
