### ISSUE TITLE
Update Fastq interlacer/de-interlacer + paired_end_joiner to fix bug with compressed inputs

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#67]
https://toolshed.g2.bx.psu.edu/view/devteam/fastq_paired_end_interlacer/ef49268ee579
https://toolshed.g2.bx.psu.edu/view/devteam/fastq_paired_end_deinterlacer/b7ce72b00e62
https://toolshed.g2.bx.psu.edu/view/devteam/fastq_paired_end_joiner/822cc1e6274e

Once applied, should fix this error with compressed inputs (still errors 12/11/17): https://github.com/galaxyproject/tools-devteam/issues/487

**Comment by martenson** [comment]
updated on Main in https://github.com/galaxyproject/usegalaxy-playbook/commit/34a4dd4815981e23ec7f3a436048cf990c3146ce

**Comment by jennaj** [comment]
Retesting (again, problems first time around)

**Comment by jennaj** [comment]
Test history: https://usegalaxy.org/u/jen/h/test-fastq-interlacer-de-interlacer

fastqsanger

 - de-interlacer 1.1.2, datasets 52-55: (running)
 - interlacer

fastqsanger.gz

 - de-interlacer 1.1.2, datasets 56-59: (running)
 - interlacer

fastqsanger.bz2

 - de-interlacer 1.1.2, datasets 60-63: (running)
 - interlacer
