### ISSUE TITLE
Update SRA tools: NCBI Download and Extract Reads in BAM + Fastq to version 2.8.1.3

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#68]
https://toolshed.g2.bx.psu.edu/view/iuc/sra_tools/8c00bc7fd8de

Two of the NCBI tools were recently updated to prevent usage errors: https://github.com/galaxyproject/tools-iuc/issues/1445

**Comment by martenson** [comment]
updated on Main in https://github.com/galaxyproject/usegalaxy-playbook/commit/34a4dd4815981e23ec7f3a436048cf990c3146ce

**Comment by jennaj** [comment]
**Download and Generate Pileup Format from NCBI SRA (Galaxy Version 2.8.1.2)**

Same test history, datasets 67-71

Dataset 70 had some sort of problem and failed: stdout states

    Fixed default configuration

    2018-03-30T01:29:34 prefetch.2.8.1: 1) Downloading 'SRR1582967'...
    2018-03-30T01:29:34 prefetch.2.8.1:  Downloading via fasp...
    2018-03-30T01:29:50 prefetch.2.8.1:  fasp download succeed
    2018-03-30T01:29:50 prefetch.2.8.1: 1) 'SRR1582967' was downloaded successfully
    2018-03-30T01:29:50 prefetch.2.8.1: 'SRR1582967' has 0 unresolved dependencies

Also fails with multiple accessions. This particular tool is not noted as accepting more than one, but the form looks very much like the others and users could get confused. Maybe help text stating to only enter one accession would help.

**Download and Extract Reads in FASTA/Q format from NCBI SRA (Galaxy Version 2.8.1.3)**

Datasets 72-77

Same results - single accession works, multiple fails.

Needs a tool fix-it tickets or is this server configuration problem? @natefoo or @davebx ?? I didn't test at usegalaxy.eu but could (and would before making a tool fix ticket)

**Comment by davebx** [comment]
@jennaj from what I can tell, specifying multiple SRAs is only supported with an input dataset containing newline-separated accessions to download, the `SRR925743 ,ERR343809` in the help text notwithstanding.

**Comment by jennaj** [comment]
@davebx Thanks for checking, I didn't understand that part. The tool form help is probably Ok as is -- but we can go back to that if more end users are confused going forward (specifically: tool help update - I'd do that and it could publish whenever the next rev is done on this tool suite). Sounds like the tool could be updated to accept an input tabular list of accessions (enhancement) but that is a much bigger change and complicates usage -- not sure I am for that right now.

Also, I just retested dataset 70 (the failed pileup data). It failed again but that can happen with this tool when the data is really large. The tool functioned on other datasets - including the form's example accession. 

Let's consider this done. Thanks again for the tool update!
