### ISSUE TITLE
Mothur tools: all logfiles have datatype "txt" but some have unparsed content and are not viewable in UI

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#70]
Occurs at https://usegalaxy.org, does not occur at https://galaxy.uni-freiburg.de

Test history: https://usegalaxy.org/u/jen/h/16s-microbial-analysis-with-mothur---proccess

Cannot reproduce at https://galaxy.uni-freiburg.de/u/jenj/h/test-history-mothur-subsample so the problem does not seem to be with the tools but possibly with config.

Search datasets by keyword "logfile" and click on the "eye" icon for a few - some display, some will only download (and have oddly formatted text when reviewed). The report content may be the source of the problem, it contains some command strings that might be interpreted as being html/code.

Dataset 175 in usegalaxy history can be directly compared to dataset 8 in freiburg history (same tool, same inputs, different server).

@davebx @bgruening @natefoo

**Comment by jennaj** [comment]
ping @guerler These are the txt files with display problems

**Comment by jennaj** [comment]
Mothur tools were all updated. Retesting.

**Comment by natefoo** [comment]
I was going to test this one but noticed that the usegalaxy.eu logfiles also download rather than display, for me.

**Comment by natefoo** [comment]
Ok, I just picked the wrong datasets to test over on usegalaxy.eu. Anyway, I this has to do with the presence of control characters in the log file and the use of nginx's `X-Accel-Redirect`. It appears that nginx passes some? (`Content-Type`) but not all (`X-Content-Type-Options`) response headers in the internal redirect to `/_x_accel_redirect`. This change to the nginx config in 25fb3498847ed52e40ac64a9833aa3eea75e2359 fixes it:

```nginx
	location /_x_accel_redirect {
		internal;
		alias /;
		add_header X-Frame-Options SAMEORIGIN;
		add_header X-Content-Type-Options nosniff;
	}
```

Ping @erasche in case you want to do the same.

**Comment by erasche** [comment]
Thanks @natefoo

**Comment by jennaj** [comment]
I went through and was able to visualize the logfile now for the first ~15 tools in that massive test history at `org`. Thanks!
