### ISSUE TITLE
Fix font problems in devteam/xy_plot tool

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#71]
MTS: https://toolshed.g2.bx.psu.edu/view/devteam/xy_plot/ecb437f1d298

Tool: Plotting Tool for multiple series and graph types | 1.0.2

Used in this GTN tutorial, section "Hands-on: Plot Rarefaction": http://galaxyproject.github.io/training-material/topics/metagenomics/tutorials/mothur-miseq-sop/tutorial.html

**Comment by jennaj** [comment]
ping @davebx

**Comment by martenson** [comment]
updated on Main in https://github.com/galaxyproject/usegalaxy-playbook/commit/34a4dd4815981e23ec7f3a436048cf990c3146ce

**Comment by jennaj** [comment]
Retesting

**Comment by jennaj** [comment]
@martenson @natefoo version 1.0.2 fails.

Does this look like a Galaxy config problem or a tool problem?

> Dataset Error
> An error occured while running the tool toolshed.g2.bx.psu.edu/repos/devteam/xy_plot/XY_Plot_1/1.0.2.
> 
> Tool execution generated the following messages:
> 
> Fontconfig warning: "/etc/fonts/fonts.conf", line 146: blank doesn't take any effect anymore. please remove it from your fonts.conf

**Comment by martenson** [comment]
@jennaj can you please share the history?

**Comment by martenson** [comment]
I propose hiding the tool and adjusting the tutorial.

**Comment by natefoo** [comment]
This can be fixed relatively easily by using exit codes instead of stderr.

The warning is caused by conda using a newer version of fontconfig than the one on the system, for which `/etc/fonts/fonts.conf` is written. There's a suitable `<env>/etc/fonts/fonts.conf` in the conda env but I can't think of a way to get `$FONTCONFIG_FILE` set properly for this.

**Comment by martenson** [comment]
@natefoo the actual error is different (can be seen in the history: https://usegalaxy.org/histories/view?id=223db61e77830a8e).

```
Error in Summary.factor(c(1L, 2L, 49L, 50L, 51L, 52L, 53L, 54L, 55L, 56L,  : 
  ‘range’ not meaningful for factors
```

**Comment by natefoo** [comment]
That's hid 516, hid 517 was successful though.

**Comment by martenson** [comment]
Oh so you think 516 had bad inputs? 517 is definitely just warning written to stderr, I can see the plot fine.

**Comment by natefoo** [comment]
Well, interesting development... fontconfig in the R conda env is correctly reading its own fonts.conf. But when we run jobs, we set `$FONTCONFIG_FILE` to `/cvmfs/main.galaxyproject.org/fontconfig/fonts.conf`, which loads some custom fonts in `/cvmfs/main.galaxyproject.org/fontconfig/fonts`. This was done long, long ago for pre-TS tools.

If I don't set `$FONTCONFIG_FILE`, it'll probably fix this tool, but I don't know what tool(s) used these fonts and whether they will break if these fonts aren't available. If I knew what tools they were, I could set `$FONTCONFIG_FILE` just for these tools.

**Comment by natefoo** [comment]
However, I am inclined to just unset this and fix any old tools it breaks as they are discovered.

**Comment by natefoo** [comment]
[Well this is interesting](https://usegalaxy.org/u/nate/h/plot-test). I ran Plotting tool, Scatterplot, and Histogram, then disabled `$FONTCONFIG_FILE` and ran all 3 again. With `$FONTCONFIG_FILE` set, Plotting tool ends in error but produces a valid plot:

![before](https://usegalaxy.org/datasets/bbd44e69cb8906b58b5df9d6509b8123/display/?preview=True "before")

With it unset, Plotting tool ends ok but the fonts in the plot are symbol fonts:

![after](https://usegalaxy.org/datasets/bbd44e69cb8906b54a3d786d444870d4/display/?preview=True "after")

Unsetting it had no effect on Scatterplot or Histogram.

I think maybe the tool should add a requirement on some font package in conda?

**Comment by jennaj** [comment]
test history (late, you found it in other ticket): https://usegalaxy.org/u/jen/h/16s-microbial-analysis-with-mothur---proccess

Dataset 517 is in an error state (red). The graph does look how I would expect it to (but can't really double check, am comparing with whatever tool version was used to create tutorial graphics, this has never been on main before and haven't checked at eu).

**Comment by jennaj** [comment]
@natefoo right, that was the problem before - red error dataset but graphics produced. If you create a ticket for a tool update, could you link it back? That might be a less risky choice (adding conda dep to tool) rather than making a change that impacts all tools.

**Comment by jennaj** [comment]
yes, hid 516 failed because of usage - The way the tool form is designed, each series input needs to have the "Header in first line?" set to yes individually. This is easy to miss, especially when doing that step in the tutorial where you add in 10+ series, each its own section. The form could be modified but considering how much other stuff is going on, is minor, so didn't report it, just the hid 517 failure.

**Comment by natefoo** [comment]
I've fixed this by installing DejaVu fonts into CVMFS and making fontconfig aware of them with `$XDG_DATA_HOME`. The process was:

1. `cvmfs_server transaction $repo && mkdir -p /cvmfs/$repo/xdg/data/fonts`
1. `curl -L http://sourceforge.net/projects/dejavu/files/dejavu/2.37/dejavu-fonts-ttf-2.37.tar.bz2 | tar jxf - -C /cvmfs/$repo/xdg/data/fonts`
1. Unset `$FONTCONFIG_FILE` and set `XDG_DATA_HOME=/cvmfs/$repo/xdg/data` in 502a0b338632c8ef8269497ca3c01dbcb54cba88

(where `$repo` is `test.galaxyproject.org` or `main.galaxyproject.org`)

**Comment by jennaj** [comment]
thanks for testing, also worked for me. changing test status.
