### ISSUE TITLE
Consider adding tool: Visualize with Krona 

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#73]
This is not in the Main Tool Shed (best guess == https://toolshed.g2.bx.psu.edu/view/saskia-hiltemann/krona_text/b14f1444e464) but is on the https://galaxy.uni-freiburg.de server. At Freiburg, when the tool is brought up, there is no link to the tool shed under "Options". Maybe just needs some tuning to connect it all up.

Full tool name: Visualize with Krona Visualise any hierarchical data (Galaxy Version 1)

Is used in the [GTN 16S metagenomics tutorial](http://galaxyproject.github.io/training-material/topics/metagenomics/tutorials/mothur-miseq-sop/tutorial.html#otu-based-analysis), Visualization section "Hands-on: Krona". The other vis option is "Hands-on: Phinch", but the tool Make.biom has a problem recognizing one of the inputs or I don't understand what datatype to assign (tested tabular, txt, and data). Ticket for that is here, once/if updated, main & freiburg would both need an upgrade: https://github.com/galaxyproject/tools-iuc/issues/1644).

Thoughts? @jxtx @nekrut @bgruening

**Comment by jennaj** [comment]
Done, closing

**Comment by shiltemann** [comment]
just FYI, with the [new mothur wrappers](https://github.com/galaxyproject/tools-iuc/pull/1722), I am including a tool to convert mothur taxonomy files to an input format that can be supplied to the iuc version of the krona tool so then this would then no longer be required (will update the tutorial as well after the mothur PR is merged)
