### ISSUE TITLE
Missing tool? Filter List from contents of a file (Galaxy Version 1.0.0)

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#75]
Not sure why this is not at Galaxy Main https://usegalaxy.org. It is at https://galaxy.uni-freiburg.de already. Maybe just an update is needed?

ping @nekrut @natefoo @davebx 

MTS Repo: None, is part of the distribution.

Related tickets: 

 - Split collection (WIP? Recently requested at https://biostar.usegalaxy.org/p/26249/): https://github.com/galaxyproject/galaxy/issues/3870
 - Alternative for split: https://github.com/galaxyproject/galaxy/issues/740
 - Filter based on file (this tool - was in 17.05?): https://github.com/galaxyproject/galaxy/pull/3940

**Comment by natefoo** [comment]
We had not updated the collection operations from the sample main tool config for a while. This was done as of 8f88cb0342a4c5ceace6511ada0732657ee5b82d.
