### ISSUE TITLE
Update Samtools Filter BAM after bug fixed and tool updated in MTS

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#77]
Issue here: https://github.com/galaxyproject/tools-devteam/issues/501

**Comment by jennaj** [comment]
Think this tool had the updated version with fix added already, but retesting to make sure

**Comment by natefoo** [comment]
I can confirm that the version you ran in https://usegalaxy.org/u/jen/h/test-history-bamcompare-deeptools-hisat (1.1.2) had the fix.

**Comment by jennaj** [comment]
Same, closing. and https://github.com/galaxyproject/usegalaxy-playbook/issues/78 was a duplicate :-/
