### ISSUE TITLE
Update Samtools Filter SAM or BAM  - it fails to split on multiple regions and a fix has been made

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#78]
The version on Main seems to be not the most current version in the MTS. The version didn't get bumped, but a fix was made to address a specific problem that presents on Main (and in local tests comparing the before/after fix versions). 

Details are here: https://github.com/galaxyproject/tools-devteam/issues/501

@davebx Is this something you would have time for? Thanks!

**Comment by martenson** [comment]
it seems Main has the latest version now

**Comment by martenson** [comment]
updated on Main in https://github.com/galaxyproject/usegalaxy-playbook/commit/34a4dd4815981e23ec7f3a436048cf990c3146ce

**Comment by natefoo** [comment]
Is this to fix the same issue as #77? i.e. are these two duplicates?

**Comment by jennaj** [comment]
Yes, closing both, sorry!

Version 1.1.2

Passed tests - dataset 16 was rerun in dataset 18 and the filter worked.

https://usegalaxy.org/u/jen/h/test-history-bamcompare-deeptools-hisat
