### ISSUE TITLE
Freebayes/BamLeftAlign 1.1.0.46-0 failing for a dependency issue

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#79]
**Current workaround until fixed**  _Use the 1.0.2.29-3 version of Freebayes or BamLeftAlign_

 - Click on Freebayes or BamLeftAlign from the left Tool Panel
 - Use the Versions menu on the loaded tool form to select `1.0.2.29-3`
 - The earlier version of the tool form will load
 - Before using, confirm the version switch is correct. The tool name/version will be noted at the very top of the tool form

**MTS** https://toolshed.g2.bx.psu.edu/view/devteam/freebayes/156b60c1530f && https://toolshed.g2.bx.psu.edu/view/devteam/bamleftalign/e65540a91b87

**Test history** Dataset 40 uses version 1.1.0.46-0 https://usegalaxy.org/u/jen/h/test-history-freebayes

**Error** 
```
Dataset Error
An error occured while running the tool toolshed.g2.bx.psu.edu/repos/devteam/freebayes/freebayes/1.1.0.46-0.

Tool execution generated the following messages:

Fatal error: Exit code 7 ()
freebayes: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory
freebayes: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory
freebayes: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory
freebayes: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory
freebayes: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory
freebayes: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory
freebayes: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory
```

**Reported by** https://biostar.usegalaxy.org/p/26363

cc @davebx Config update is needed pls, thanks!

**Comment by natefoo** [comment]
Fixed as of some time on 2/14/2018 I believe. This was again due to our old version of Conda (Main was on 3.19 until last week) which did not take channel ordering in to account when resolving dependencies.

**Comment by jennaj** [comment]
Testing at Galaxy main https://usegalaxy.org shows that both tools are fixed, too. Thanks & closing out!
