### ISSUE TITLE
is shed_tool_conf.xml out of date

### ISSUE THREAD

**Issue by mictadlo** [galaxyproject/usegalaxy-playbook#8]
I found this [shed_tool_conf.xml](https://raw.githubusercontent.com/galaxyproject/usegalaxy-playbook/c55aa042825fe02ef4a02d958eb811adba8ea45f/files/galaxy/usegalaxy.org/var/shed_tool_conf.xm) file on use galaxy-playbook. I copied information for snpSift_filter out of the xml file and pasted it to the command below:

    $ python /Users/lorencm/galaxy/scripts/api/install_tool_shed_repositories.py -a 4bb8f6eb85efca463d2e60b9704d6caf -l http://localhost:8080  -n snpSift_filter -o pcingola -r c052639fa666 --panel-section-name 'snpEff' --repository-deps --tool-deps -u http://toolshed.g2.bx.psu.edu/

However, I received the following error massage:

    HTTP Error 400: Bad Request
    {"traceback": "Traceback (most recent call last):\n  File \"/Users/lorencm/galaxy/lib/galaxy/web/framework/decorators.py\", line 251, in decorator\n    rval = func( self, trans, *args, **kwargs)\n  File \"/Users/lorencm/galaxy/lib/galaxy/webapps/galaxy/api/tool_shed_repositories.py\", line 246, in install_repository_revision\n    payload )\n  File \"/Users/lorencm/galaxy/lib/tool_shed/galaxy_install/install_manager.py\", line 704, in install\n    changeset_revision )\n  File \"/Users/lorencm/galaxy/lib/tool_shed/galaxy_install/install_manager.py\", line 505, in __get_install_info_from_tool_shed\n    raise exceptions.RequestParameterInvalidException( invalid_parameter_message )\nRequestParameterInvalidException: No information is available for the requested repository revision.\nOne or more of the following parameter values is likely invalid:\ntool_shed_url: http://toolshed.g2.bx.psu.edu/\nname: snpSift_filter\nowner: pcingola\nchangeset_revision: c052639fa666\n\n", "err_msg": "No information is available for 

What did I do wrong?

Thank you in advance.

Mic

**Comment by bgruening** [comment]
@mictadlo you can only install repositories. You have specified a tool that is inside of a repository called `snpeff`
Does this work for you?

`$ python /Users/lorencm/galaxy/scripts/api/install_tool_shed_repositories.py -a 4bb8f6eb85efca463d2e60b9704d6caf -l http://localhost:8080  -n snpeff -o pcingola --panel-section-name 'snpEff' --repository-deps --tool-deps -u http://toolshed.g2.bx.psu.edu/`

But the way this `snpeff` version is really old you should use the IUC one.

**Comment by mictadlo** [comment]
Thank you it is working now. Where is it possible to get an up to date list of tools which are new and stable?

**Comment by bgruening** [comment]
@mictadlo the [Tool Shed](http://toolshed.g2.bx.psu.edu/) is the up to date list of tools. The problem is to figure out which repository/tool you need. It's like an AppStore you need to figure out which one is the best. I admit this is hard sometimes and we (as community) should do a better job at rating repositories. Imho all repositories from devteam and IUC are high quality,
