### ISSUE TITLE
Update Bowtie2 from version 2.3.2.2 to 2.3.4.1 - includes important bug fixes

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#81]
~~Version 2.3.4 is the most current in the MTS (2018-1-20): 
https://toolshed.g2.bx.psu.edu/view/devteam/bowtie2/97d1923c8c4b~~

**Update** 2.3.4.1 is the most current in the MTS (2018-1-23):
https://toolshed.g2.bx.psu.edu/view/devteam/bowtie2/dc1639b66f12

This new version addresses full parameter functionality and related fixes: https://github.com/galaxyproject/tools-iuc/commits/master/tools/bowtie2

~~A report of a problem has come in, but it is not clear which tool version/Galaxy release produced that yet. I am going to test `Bowtie2 2.3.3.1` in `Galaxy 17.09` to see if I can reproduce it.~~

**Update:** Problems confirmed with a subset of options (https://biostar.usegalaxy.org/p/26384/), issue ticket opened: https://github.com/galaxyproject/tools-iuc/issues/1684

**Workaround:** avoid versions 2.3.3.1 and 2.3.4 if you need to use the problematic options.

**Comment by jennaj** [comment]
This is ready to update on Main - v 2.3.4.1 in the MTS has the bug fix.

**Comment by martenson** [comment]
updated on Main in https://github.com/galaxyproject/usegalaxy-playbook/commit/34a4dd4815981e23ec7f3a436048cf990c3146ce

**Comment by jennaj** [comment]
Bowtie2 - map reads against reference genome (Galaxy Version 2.3.4.1)

Passes tests, including the bug fix. Run with a paired-end collection.

Test history, data 22-38: https://usegalaxy.org/u/jen/h/test-history-bowtie2
