### ISSUE TITLE
Update to NucBed 2.27.0.1 to capture a bug fix

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#83]
Details: https://github.com/galaxyproject/tools-iuc/issues/1662

Might need to wait for one more fix, the conda env has problems in some tests (also included in the linked ticket above).

**Comment by martenson** [comment]
updated on Main in https://github.com/galaxyproject/usegalaxy-playbook/commit/34a4dd4815981e23ec7f3a436048cf990c3146ce

**Comment by jennaj** [comment]
Retesting again (original test *somewhere*, didn't make it back here) and will close out

**Comment by jennaj** [comment]
Passed tests at `org`, so closing. If `eu` doesn't pass, will report it back to the iuc ticket. Closing, thanks!
