### ISSUE TITLE
problems with trying to download a collections using curl or wget

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#85]
Not sure if this is just at https://usegalaxy.org or not yet.

Example:

> $ curl -o coll.txt --insecure 'https://usegalaxy.org/api/histories/7d13d47c3adf0775/contents/dataset_collections/966df8d0c0192f91/download'
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100    79    0    79    0     0    286      0 --:--:-- --:--:-- --:--:--   285
> $ more coll.txt
> {"err_msg": "API authentication required for this request", "err_code": 403001}

and

> $ wget -O --no-check-certificate 'https://usegalaxy.org/api/histories/7d13d47c3adf0775/contents/dataset_collections/966df8d0c0192f91/download'
> --2018-01-25 15:03:32--  https://usegalaxy.org/api/histories/7d13d47c3adf0775/contents/dataset_collections/966df8d0c0192f91/download
> Resolving usegalaxy.org... 129.114.60.60, 129.114.60.56
> Connecting to usegalaxy.org|129.114.60.60|:443... connected.
> HTTP request sent, awaiting response... 403 Forbidden
> 2018-01-25 15:03:33 ERROR 403: Forbidden.

Might be related:  https://github.com/galaxyproject/galaxy/issues/5059

And makes the workaround here non-functional: https://github.com/galaxyproject/galaxy/issues/3195

ping @natefoo

**Comment by jennaj** [comment]
The permissions problem is resolved but the downloaded content is HTML.

**Comment by jennaj** [comment]
@mvdbeek John suggested that you might be able to help.

```
$ curl -o coll3.txt --insecure 'https://usegalaxy.org/datasets/bbd44e69cb8906b5d53a189ef2afc169/display?to_ext=txt&hdca_id=966df8d0c0192f91&element_identifier=M117C1-ch'
 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                Dload  Upload   Total   Spent    Left  Speed
100  4995    0  4995    0     0  13277      0 --:--:-- --:--:-- --:--:-- 13284
$ head coll3.txt




<!DOCTYPE HTML>
<html>
   <!--base.mako-->

.....many more lines.....
```

**Comment by jmchilton** [comment]
You don't have an API key or session information in in there - I'm not sure how curl would have permissions to do this. Does this work with regular datasets outside of collections?

**Comment by martenson** [comment]
The link from example (https://usegalaxy.org/api/histories/7d13d47c3adf0775/contents/dataset_collections/966df8d0c0192f91/download) works for me and downloads a zipped folder with 4 datasets. This looks more like an issue with curl?

**Comment by jennaj** [comment]
Ok, let me try wget. I'm using the syntax here: 

Works on individual files:

```
$ curl -o fqdata44.txt --insecure 'https://usegalaxy.org/datasets/bbd44e69cb8906b5162eb5d1d52b5335/display?to_ext=fastqsanger'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  207M  100  207M    0     0  12.1M      0  0:00:17  0:00:17 --:--:-- 10.9M
$ head fqdata44.txt
@M01368:20:000000000-A46F5:1:1101:10294:8369/2
CTCCAGGCCCATAACACTTGGGGGTAGCTAAAGTGAACTGTATCCGACATCTGGTTCCTACTTCAGGGCCATAAAGCCTAAATAGCCCACACGTTCCCCTTAAATAAGACATCACGATGGATCACAGGTCTATCACCCTATTAACCACTCACGGGAGCTCTCCATGCATTTGGTATTTTCGTCTGGGGGGTATGCACGCGATAGCATTGCGAGACGCTGGAGCCGGAGCACCCTATGTCGCAGTAT
+
BBCCCFFCCCCFGGGGGGGGGGGGGGGHHHHHGHHHHHHHHHHHHGGGGGHHHHHHHHHFHGHHHHGGGGCHGHHHHEHFHFHHGHHHHGGGGHHHHHHHHHHFHHFHHGHHHHHGGHGGHHHHHHGHGGGHHHHHHHGFHHGFHHHGHHHHHGGFGGHGHHHHHHHHHHHGHHEHHHHHGHGHGHGGGFFFFFFFFFFFFFDFFFFFFFF;D=DDFFFA.AFFFAA;A.;.AAFFFBBEECDFEF
@M01368:20:000000000-A46F5:1:1101:10302:11041/2
TATTATGTCCTACAAGCATTAATTAATTAACACACTTTAGTAAGTATGTTCGCCTGTAATATTGAACGTAGGTGCGATAAATAATGGGATGAGGCAGGAATCAAAGACAGATACTGCGACATAGGGTGCTCCGGCTCCAGCGTCTCGCAATGCTATCGCGTGCATACCCCCCAGACGAAAATACCAAATGCATGGAGAGCTCCCGTGAGTGGTTAATAGGGTGATAGACCTGTGATCCATCGTGATGTCTT
+
BCCCDFFFFFFFGGGGGGGGGGHHHHHHHHHHHHGHHHHHGHHHHHHHHHHGGGGHHHHHIIHHGHHGHHHGHHHGGHGGHHHHHHHHFHGGHHGGGGGHHHHHHHHHHHHHHHHHHGGGGGHHGGFFGHHHGGGGGGHHHGGGGHHGGFGHHHHHHGGGGGGHHHHHHHGGGGHGECGDGHHHHHHFFFGGGGGGFGGGGGGFDEGFGBBEFGGBFGGFF/AEFFFFFFFFFBFFFFFFFDAFFFF0F0F
@M01368:20:000000000-A46F5:1:1101:11532:19548/2
AAATAAGACATCACGATGGATCACAGGTCTATCACCCTACTAACCACTCACGGGAGCTCTCCATGCATTTGGTATTTTCGTCTGGGGGGTATGCACGCGATAGCATTGCGAGACGCTGGAGCCGGAGCACCCTATGTCGCAGTATCTGTCTTTGATTCCTGCCTCATCCCATTATTTATCGCACCTACGT
```

**Comment by jennaj** [comment]
Ok - this seems like a usage problem. Different behavior for what would appear to users to be the same function: disc icon that can be clicked on to download or capture the URL for unix retrieval. 

Thoughts on that?

**Comment by martenson** [comment]
And download of the elements of a collection fails for similar reasons: `History is not accessible by user` - again, this is different from normal non-collection datasets.

I would call this a missing feature/bug. Datasets should not behave this differently just because they are part of a collection.

**Comment by jennaj** [comment]
@martenson Could you open a ticket and link this one back? Then I can close this out and deal with the Hub documentation issues separately. In short, state that the curl/wget only works on non-collection data in the FAQ.

**Comment by martenson** [comment]
@jennaj yeah

**Comment by martenson** [comment]
I improved the docs to include the info about API key need for collection/(contents) and opened a ticket linked above to track bringing collections on par with normal dataset sharing. Closing.
