### ISSUE TITLE
VCF datasets fail local IGV loading

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#89]
**Reported by:** https://biostar.usegalaxy.org/p/26506/

**Using:** [IGV](https://software.broadinstitute.org/software/igv/download) version `2.4.7` and Galaxy version `17.09, commit a82d325d18375797ce8ab53366320f3c9a772ab7`

**Test history:** https://usegalaxy.org/u/jen/h/test-history-igv-local

**Known issue:** Might be related, involves Freebayes/VCF in the most current wrapper version (but not the Freebayes wrapper version used in these tests). That failure is the test history as dataset 40 and is tracked here: https://github.com/galaxyproject/usegalaxy-playbook/issues/79

**Tests:**

----

1. **Fasta** in dataset 45 and **BED12/BED6** in datasets 49/50 prepared and loaded fine.

----

2. **Freebayes VCF** in dataset 41 is assigned to a **natively indexed genome/database** on the server. Preparing the data for IGV results in a metadata problem. Could this be related to the other problems tools are having with duplicated dbkeys? https://github.com/galaxyproject/usegalaxy-playbook/issues/55
<img width="760" alt="screen shot 2018-01-29 at 5 10 39 pm" src="https://user-images.githubusercontent.com/8999735/35543294-28d0c372-0519-11e8-995f-456765c459e8.png">

----

3. **NVC VCF** in dataset 47 is also assigned to a **natively indexed genome/database** on the server (different dbkey). Same metadata problem. 

----

4. **Freebayes VCF** in dataset 53 is assigned to a **custom build genome/database** on the server. Both BAM and CG filtered to just human_chrM (hg19 version). _Status pending - job still running._

----

**Comment by jennaj** [comment]
Problems are still present, we might want to merge these or at least reference both when fixed.

https://github.com/galaxyproject/usegalaxy-playbook/issues/122

**Comment by jennaj** [comment]
Was this addressed in 18.05 (in a change not on main yet), or are we planning to resolve this?

**Comment by natefoo** [comment]
I imported your history and ran IGV and both metadata files appear to have worked. Can you see if it works for you?

**Comment by jennaj** [comment]
Had problems with stale indexes earlier (why test result was delayed) but figured it out now, thanks!

**One needs to make a copy of the history in order to clear the prior IGV cache and recreate the intermediate indexes**. Seems like it would be better to have those cleared by Galaxy automatically. The problem comes up if the track loading to IGV failed the first try for one or both pre-processing steps. Let's revisit this if users report it and create a distinct ticket for it - probably won't come up very often going forward.

Closing.
