### ISSUE TITLE
Prokka 1.12.0 failing with dep problem (Java version)

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#90]
**Tool**: **Prokka** prokaryotic genome annotation (Galaxy Version **1.12.0**)

**MTS**: https://toolshed.g2.bx.psu.edu/view/crs4/prokka/a17498c603ec

_Is the IUC version from the MTS really what is installed? The error indicates that it isn't. Should it be?_

**Current Fail** 

command line
> prokka --cpus ${GALAXY_SLOTS:-8} --quiet --outdir outdir --prefix prokka --locustag 'PROKKA' --increment 1 --gffver 3 --mincontig 200 --genus 'Staphylococcus' --species 'saprophyticus' --kingdom Bacteria --gcode 11 --evalue 1e-06 /galaxy-repl/main/files/XXX/XXX/dataset_XXX.dat

error

> Fatal error: Exit code 2 ()
> Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/galaxy-repl/main/jobdir/XXX/XXX/XXX/_job_tmp -Xmx30g  -Xms256m
> [tbl2asn] This copy of tbl2asn is more than a year old.  Please download the current version.
> Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/galaxy-repl/main/jobdir/XXX/XXX/XXX/_job_tmp -Xmx30g  -Xms256m
> [05:59:28] Could not run command: tbl2asn -V b -a r10k -l paired-ends -M n -N 1 -y 'Annotated using prokka 1.12 from https://github.com/tseemann/prokka' -Z outdir\/prokka\.err -i outdir\/prokka\.fsa 2> /dev/null

**Prior success** (rerunning this jobs again to see if rerun fails now, will update once done)

command line
> prokka --cpus ${GALAXY_SLOTS:-8} --quiet --outdir outdir --prefix prokka --locustag 'PROKKA' --increment 1 --gffver 3 --mincontig 200 --genus 'Escherichia' --species 'coli' --strain 'C-1' --kingdom Bacteria --gcode 11 --usegenus --evalue 1e-06 /galaxy-repl/main/files/XXX/XXX/dataset_XXX.dat

ping @natefoo @davebx

**Comment by bgruening** [comment]
I had the same problem yesterday on our server. @natefoo please change into the envs and do `conda update tbl2asn`. The problem here is that tbl2asn has a build-int deprecation mode. If the binary is older then a year you can not execute it anymore. Either we reset the cock or we need to update the binary. Its very bad for reproducibility but on the other site this tool is used for NCBI annotations and they do not want to have old bugs to manually curate.

**Comment by natefoo** [comment]
Ok, I have updated tbl2asn in Main's `__prokka@1.12` env (and Test's `__prokka@1.11`) as of just now. Thanks @bgruening!

**Comment by jennaj** [comment]
Passes GUI tests on Main, closing this out. Thanks everyone!

**Comment by natefoo** [comment]
It's worth recording that we will have the same problem in another year. The long term solution is to build a copy of tbl2asn that bypasses the check.
