### ISSUE TITLE
Update Main and Test with GenomeSpace Importer/Exporter fix

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#92]
https://github.com/galaxyproject/galaxy/issues/5527

ping @martenson @davebx

**Comment by natefoo** [comment]
Test was updated at 15 Feb 2018 20:07:59 UTC.
Main was updated at 16 Feb 2018 15:53:42 UTC.

(with a few minutes' delay until everything propagated and restarted).

**Comment by natefoo** [comment]
They are now temporarily disabled due to some problems with the tool, they should be back soon.

**Comment by jennaj** [comment]
New tool update now tracked here: https://github.com/galaxyproject/usegalaxy-playbook/issues/100
