### ISSUE TITLE
Update Replace Text tool once MTS updated to reflect bug fix in dev repo

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#93]
https://github.com/bgruening/galaxytools/commit/8d726e6220e7a8eda407efaecf762cb8e0090d34

> Tool ID | toolshed.g2.bx.psu.edu/repos/bgruening/text_processing/tp_replace_in_line/1.1.0
> Tool Version | 1.1.0
> Job Tool Version | sed (GNU sed) 4.2.2.165-6e76-dirty

a gentle reminder for @natefoo @davebx 

Once updated at Test/Main, ping me here and I'll re-test to make sure all is Ok.

----

Notes:

Bug report error title includes: (tp_replace_in_line) 

Test history: *pending*

```
Use case
Find pattern | ACTG 
Replace with: | xyz
```

```
Command Line
sed -r --sandbox 's?ACTG?xyz?g' '/galaxy-repl/main/files/XXX/XXX/dataset_XXX.dat' > '/galaxy-repl/main/files/XXX/XXX/dataset_XXX.dat'
stderr
sed: -e expression #1, char 2: delimiter character is not a single-byte character
```

**Comment by natefoo** [comment]
I've updated these on Main.

**Comment by jennaj** [comment]
Thanks, testing in progress.

**Comment by jennaj** [comment]
Tested all three tools on variably formatted txt and tabular datasets. 

> Text Manipulation
> 
> - Replace parts of text
> - Replace Text in entire line
> - Replace Text in a specific column

Test history: https://usegalaxy.org/u/jen/h/test-history-data-manipulations

1) **Tests pass**

2) Unexpectedly, _Replace Text in entire line_ only modifies the first occurrence of a pattern. Might be by design, but that is not made clear on the tool form. The two other tools will replace all matches, per column or per line, so the functionality is covered. **Tool form help needs update in a PR.** 

3) Had to share the history twice to get the share link to "stick". To reproduce, share any history by link. Go back to _History > Share or Publish_, the history is not shared. Share it again, go back to _History > Share of Publish_, the share link is persistent. Both _publish share_ sticks and _direct email_ share sticks the first time. **Function for _link share_ needs a ticket.**
