### ISSUE TITLE
Update HISAT2 to current MTS version 2.1.0 -- main has 2.0.5.2

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#96]
Current version on main (Galaxy Version 2.0.5.2)

MTS https://toolshed.g2.bx.psu.edu/view/iuc/hisat2/40e1083a4430

ping @natefoo @davebx

**Comment by davebx** [comment]
Hisat2 has been updated to 2.1.0 on main.

**Comment by jennaj** [comment]
Thank you Dave, tool test passes! (used defaults)

Test history: https://usegalaxy.org/u/jen/h/test-history-hisat2-2052

I noticed that one of the prior versions (2.0.5.2) is not available under Versions anymore. Not sure if on purpose or not. @davebx could you confirm that was intended? Then we can close this out.

**Comment by davebx** [comment]
@jennaj 2.0.5.2 was not intentionally removed by me, and as of this second, is available in the versions.

**Comment by jennaj** [comment]
Ok, I see all versions now. Thanks!! Closing this out
